==14093== Memcheck, a memory error detector
==14093== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==14093== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==14093== Command: python toy.py
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x157BFF: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x1EB285: ??? (in /usr/bin/python2.7)
==14093==    by 0x21203A: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F45A7: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A56: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E5E10: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==14093==    by 0x1E79E7: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E777D: PyObject_Call (in /usr/bin/python2.7)
==14093==    by 0x2077FF: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==14093==    by 0x200C09: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x1FB628: PyEval_EvalCode (in /usr/bin/python2.7)
==14093==  Address 0x60cc020 is 64 bytes inside a block of size 200 free'd
==14093==    at 0x4C31D2F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1D6C71: ??? (in /usr/bin/python2.7)
==14093==    by 0x1D68B4: PyList_Append (in /usr/bin/python2.7)
==14093==    by 0x1F4BAD: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EF8: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4A35: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==14093==    by 0x1F49E2: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==14093==    by 0x1F4930: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4548: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A56: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E5E10: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==14093==  Block was alloc'd at
==14093==    at 0x4C31D2F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1D6C71: ??? (in /usr/bin/python2.7)
==14093==    by 0x1D68B4: PyList_Append (in /usr/bin/python2.7)
==14093==    by 0x1F4BAD: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4F61: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EE2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4A35: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==14093==    by 0x1F49E2: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==14093==    by 0x1F4930: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4548: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A56: ??? (in /usr/bin/python2.7)
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x157BFF: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x211FF5: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F45A7: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A56: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E5E10: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==14093==    by 0x1E79E7: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E777D: PyObject_Call (in /usr/bin/python2.7)
==14093==    by 0x2077FF: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==14093==    by 0x200C09: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x1FB628: PyEval_EvalCode (in /usr/bin/python2.7)
==14093==    by 0x1FB564: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==14093==  Address 0x6124020 is 1,024 bytes inside a block of size 2,711 free'd
==14093==    at 0x4C30D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1F49ED: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==14093==    by 0x1F4930: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4548: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A56: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E5E10: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==14093==    by 0x1E79E7: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E777D: PyObject_Call (in /usr/bin/python2.7)
==14093==    by 0x2077FF: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==14093==    by 0x200C09: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x1FB628: PyEval_EvalCode (in /usr/bin/python2.7)
==14093==  Block was alloc'd at
==14093==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1F49B8: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==14093==    by 0x1F4930: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4548: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A56: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E5E10: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==14093==    by 0x1E79E7: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E777D: PyObject_Call (in /usr/bin/python2.7)
==14093==    by 0x2077FF: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==14093==    by 0x200C09: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x1FB628: PyEval_EvalCode (in /usr/bin/python2.7)
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x157BFF: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x211FF5: ??? (in /usr/bin/python2.7)
==14093==    by 0x1EB16B: ??? (in /usr/bin/python2.7)
==14093==    by 0x212017: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F45A7: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A56: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E5E10: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==14093==    by 0x1E79E7: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E777D: PyObject_Call (in /usr/bin/python2.7)
==14093==    by 0x2077FF: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==14093==    by 0x200C09: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==  Address 0x6112020 is 864 bytes inside a block of size 1,008 free'd
==14093==    at 0x4C31D2F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1D6C71: ??? (in /usr/bin/python2.7)
==14093==    by 0x1D68B4: PyList_Append (in /usr/bin/python2.7)
==14093==    by 0x1F4BAD: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EE2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4A35: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==14093==    by 0x1F49E2: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==14093==    by 0x1F4930: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4548: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A56: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E5E10: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==14093==  Block was alloc'd at
==14093==    at 0x4C31D2F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1D6C71: ??? (in /usr/bin/python2.7)
==14093==    by 0x1D68B4: PyList_Append (in /usr/bin/python2.7)
==14093==    by 0x1F4BAD: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EF8: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EE2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4A35: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==14093==    by 0x1F49E2: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==14093==    by 0x1F4930: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4548: ??? (in /usr/bin/python2.7)
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x157BFF: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x1EB285: ??? (in /usr/bin/python2.7)
==14093==    by 0x212017: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F45A7: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A56: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E5E10: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==14093==    by 0x1E79E7: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E777D: PyObject_Call (in /usr/bin/python2.7)
==14093==    by 0x2077FF: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==14093==    by 0x200C09: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x1FB628: PyEval_EvalCode (in /usr/bin/python2.7)
==14093==  Address 0x60c0020 is 10,896 bytes inside a block of size 11,385 free'd
==14093==    at 0x4C30D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1F49ED: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==14093==    by 0x1F4930: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4548: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A56: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E5E10: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==14093==    by 0x1E79E7: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E777D: PyObject_Call (in /usr/bin/python2.7)
==14093==    by 0x2077FF: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==14093==    by 0x200C09: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x1FB628: PyEval_EvalCode (in /usr/bin/python2.7)
==14093==  Block was alloc'd at
==14093==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1F49B8: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==14093==    by 0x1F4930: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4548: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A56: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E5E10: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==14093==    by 0x1E79E7: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E777D: PyObject_Call (in /usr/bin/python2.7)
==14093==    by 0x2077FF: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==14093==    by 0x200C09: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x1FB628: PyEval_EvalCode (in /usr/bin/python2.7)
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x157BFF: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x212203: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F45A7: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A56: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E5E10: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==14093==    by 0x1E79E7: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E777D: PyObject_Call (in /usr/bin/python2.7)
==14093==    by 0x2077FF: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==14093==    by 0x200C09: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x1FB628: PyEval_EvalCode (in /usr/bin/python2.7)
==14093==    by 0x1FB564: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==14093==  Address 0x60c2020 is 368 bytes inside a block of size 1,008 free'd
==14093==    at 0x4C31D2F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1D6C71: ??? (in /usr/bin/python2.7)
==14093==    by 0x1D68B4: PyList_Append (in /usr/bin/python2.7)
==14093==    by 0x1F4BAD: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D58: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EF8: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EE2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4A35: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==14093==    by 0x1F49E2: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==14093==    by 0x1F4930: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4548: ??? (in /usr/bin/python2.7)
==14093==  Block was alloc'd at
==14093==    at 0x4C31D2F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1D6C71: ??? (in /usr/bin/python2.7)
==14093==    by 0x1D68B4: PyList_Append (in /usr/bin/python2.7)
==14093==    by 0x1F4BAD: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EE2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EE2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4A35: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==14093==    by 0x1F49E2: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==14093==    by 0x1F4930: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4548: ??? (in /usr/bin/python2.7)
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x157BFF: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x2120E6: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F45A7: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A56: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E5E10: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==14093==    by 0x1E79E7: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E777D: PyObject_Call (in /usr/bin/python2.7)
==14093==    by 0x2077FF: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==14093==    by 0x200C09: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x1FB628: PyEval_EvalCode (in /usr/bin/python2.7)
==14093==    by 0x1FB564: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==14093==  Address 0x6225020 is 4,144 bytes inside a block of size 4,784 free'd
==14093==    at 0x4C30D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1DCF74: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4A4F: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==14093==    by 0x1F49E2: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==14093==    by 0x1F4930: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4548: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A56: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E5E10: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==14093==    by 0x1E79E7: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E777D: PyObject_Call (in /usr/bin/python2.7)
==14093==    by 0x2077FF: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==14093==    by 0x200C09: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==  Block was alloc'd at
==14093==    at 0x4C31D2F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1D6C71: ??? (in /usr/bin/python2.7)
==14093==    by 0x1D68B4: PyList_Append (in /usr/bin/python2.7)
==14093==    by 0x1F4BAD: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EE2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4A35: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==14093==    by 0x1F49E2: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==14093==    by 0x1F4930: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4548: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A56: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E5E10: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x1FAC3A: PyGrammar_AddAccelerators (in /usr/bin/python2.7)
==14093==    by 0x1FA2EE: ??? (in /usr/bin/python2.7)
==14093==    by 0x2594C9: PyParser_ASTFromString (in /usr/bin/python2.7)
==14093==    by 0x2593B5: PyRun_StringFlags (in /usr/bin/python2.7)
==14093==    by 0x206A94: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x203C37: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x2035FD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x203231: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x203231: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==  Address 0x625f020 is 464 bytes inside a block of size 676 free'd
==14093==    at 0x4C30D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1FAC6F: PyGrammar_AddAccelerators (in /usr/bin/python2.7)
==14093==    by 0x1FA2EE: ??? (in /usr/bin/python2.7)
==14093==    by 0x2594C9: PyParser_ASTFromString (in /usr/bin/python2.7)
==14093==    by 0x2593B5: PyRun_StringFlags (in /usr/bin/python2.7)
==14093==    by 0x206A94: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x203C37: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x2035FD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x203231: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x203231: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==  Block was alloc'd at
==14093==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1FAD7E: PyGrammar_AddAccelerators (in /usr/bin/python2.7)
==14093==    by 0x1FA2EE: ??? (in /usr/bin/python2.7)
==14093==    by 0x2594C9: PyParser_ASTFromString (in /usr/bin/python2.7)
==14093==    by 0x2593B5: PyRun_StringFlags (in /usr/bin/python2.7)
==14093==    by 0x206A94: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x203C37: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x2035FD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x203231: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x203231: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093== 
==14093== Conditional jump or move depends on uninitialised value(s)
==14093==    at 0x1F752D: ??? (in /usr/bin/python2.7)
==14093==    by 0x2594C9: PyParser_ASTFromString (in /usr/bin/python2.7)
==14093==    by 0x2593B5: PyRun_StringFlags (in /usr/bin/python2.7)
==14093==    by 0x206A94: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x203C37: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x2035FD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x203231: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x203231: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x1FB628: PyEval_EvalCode (in /usr/bin/python2.7)
==14093== 
==14093== Use of uninitialised value of size 8
==14093==    at 0x1F7545: ??? (in /usr/bin/python2.7)
==14093==    by 0x2594C9: PyParser_ASTFromString (in /usr/bin/python2.7)
==14093==    by 0x2593B5: PyRun_StringFlags (in /usr/bin/python2.7)
==14093==    by 0x206A94: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x203C37: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x2035FD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x203231: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x203231: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x1FB628: PyEval_EvalCode (in /usr/bin/python2.7)
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x222BF8: ??? (in /usr/bin/python2.7)
==14093==    by 0x259489: PyParser_ASTFromString (in /usr/bin/python2.7)
==14093==    by 0x2593B5: PyRun_StringFlags (in /usr/bin/python2.7)
==14093==    by 0x206A94: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x203C37: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x2035FD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x203231: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x203231: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x1FB628: PyEval_EvalCode (in /usr/bin/python2.7)
==14093==  Address 0x62bb020 is 32,976 bytes inside a block of size 36,032 free'd
==14093==    at 0x4C30D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1F96DB: ??? (in /usr/bin/python2.7)
==14093==    by 0x2594C9: PyParser_ASTFromString (in /usr/bin/python2.7)
==14093==    by 0x2593B5: PyRun_StringFlags (in /usr/bin/python2.7)
==14093==    by 0x206A94: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x203C37: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x2035FD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x203231: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x203231: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==  Block was alloc'd at
==14093==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1F69EA: ??? (in /usr/bin/python2.7)
==14093==    by 0x2594C9: PyParser_ASTFromString (in /usr/bin/python2.7)
==14093==    by 0x2593B5: PyRun_StringFlags (in /usr/bin/python2.7)
==14093==    by 0x206A94: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x203C37: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x2035FD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x203231: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x203231: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093== 
==14093== Conditional jump or move depends on uninitialised value(s)
==14093==    at 0x157C08: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x1D7700: PyDict_SetItem (in /usr/bin/python2.7)
==14093==    by 0x20C2EF: PyFrame_FastToLocals (in /usr/bin/python2.7)
==14093==    by 0x25912F: PyEval_GetLocals (in /usr/bin/python2.7)
==14093==    by 0x206995: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x203C37: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x2035FD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x203231: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x203231: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093== 
==14093== Use of uninitialised value of size 8
==14093==    at 0x157C1C: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x1D7700: PyDict_SetItem (in /usr/bin/python2.7)
==14093==    by 0x20C2EF: PyFrame_FastToLocals (in /usr/bin/python2.7)
==14093==    by 0x25912F: PyEval_GetLocals (in /usr/bin/python2.7)
==14093==    by 0x206995: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x203C37: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x2035FD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x203231: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x203231: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x15FB0A: ??? (in /usr/bin/python2.7)
==14093==    by 0x22F589: ??? (in /usr/bin/python2.7)
==14093==    by 0x230648: ??? (in /usr/bin/python2.7)
==14093==    by 0x22CE86: ??? (in /usr/bin/python2.7)
==14093==    by 0x224B92: PyAST_Compile (in /usr/bin/python2.7)
==14093==    by 0x22C604: ??? (in /usr/bin/python2.7)
==14093==    by 0x2593D5: PyRun_StringFlags (in /usr/bin/python2.7)
==14093==    by 0x206A94: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x203C37: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x2035FD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==  Address 0x62d0020 is 368 bytes inside a block of size 464 free'd
==14093==    at 0x4C31D2F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1D6C71: ??? (in /usr/bin/python2.7)
==14093==    by 0x210BF8: PyArena_AddPyObject (in /usr/bin/python2.7)
==14093==    by 0x20EC1E: ??? (in /usr/bin/python2.7)
==14093==    by 0x20F62C: ??? (in /usr/bin/python2.7)
==14093==    by 0x20EF77: ??? (in /usr/bin/python2.7)
==14093==    by 0x20EBBE: ??? (in /usr/bin/python2.7)
==14093==    by 0x20CE7A: ??? (in /usr/bin/python2.7)
==14093==    by 0x20B0A1: PyAST_FromNode (in /usr/bin/python2.7)
==14093==    by 0x25947E: PyParser_ASTFromString (in /usr/bin/python2.7)
==14093==    by 0x2593B5: PyRun_StringFlags (in /usr/bin/python2.7)
==14093==    by 0x206A94: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==  Block was alloc'd at
==14093==    at 0x4C31D2F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1D6C71: ??? (in /usr/bin/python2.7)
==14093==    by 0x210BF8: PyArena_AddPyObject (in /usr/bin/python2.7)
==14093==    by 0x20ED1A: ??? (in /usr/bin/python2.7)
==14093==    by 0x20EBBE: ??? (in /usr/bin/python2.7)
==14093==    by 0x20D00F: ??? (in /usr/bin/python2.7)
==14093==    by 0x20B0A1: PyAST_FromNode (in /usr/bin/python2.7)
==14093==    by 0x25947E: PyParser_ASTFromString (in /usr/bin/python2.7)
==14093==    by 0x2593B5: PyRun_StringFlags (in /usr/bin/python2.7)
==14093==    by 0x206A94: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x203C37: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x157BFF: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x234FE9: ??? (in /usr/bin/python2.7)
==14093==    by 0x224A94: PyAST_Compile (in /usr/bin/python2.7)
==14093==    by 0x22C604: ??? (in /usr/bin/python2.7)
==14093==    by 0x2593D5: PyRun_StringFlags (in /usr/bin/python2.7)
==14093==    by 0x206A94: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x203C37: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x2035FD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x203231: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x203231: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==  Address 0x62d3020 is 496 bytes inside a block of size 549 free'd
==14093==    at 0x4C31D2F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1EAF17: _PyString_Resize (in /usr/bin/python2.7)
==14093==    by 0x23461F: ??? (in /usr/bin/python2.7)
==14093==    by 0x224A94: PyAST_Compile (in /usr/bin/python2.7)
==14093==    by 0x22C604: ??? (in /usr/bin/python2.7)
==14093==    by 0x2593D5: PyRun_StringFlags (in /usr/bin/python2.7)
==14093==    by 0x206A94: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x203C37: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x2035FD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x203231: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==  Block was alloc'd at
==14093==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x15FB60: ??? (in /usr/bin/python2.7)
==14093==    by 0x1EAF17: _PyString_Resize (in /usr/bin/python2.7)
==14093==    by 0x235339: ??? (in /usr/bin/python2.7)
==14093==    by 0x224A94: PyAST_Compile (in /usr/bin/python2.7)
==14093==    by 0x22C604: ??? (in /usr/bin/python2.7)
==14093==    by 0x2593D5: PyRun_StringFlags (in /usr/bin/python2.7)
==14093==    by 0x206A94: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x203C37: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x2035FD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x157BFF: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x238A13: ??? (in /usr/bin/python2.7)
==14093==    by 0x238795: ??? (in /usr/bin/python2.7)
==14093==    by 0x224A9F: PyAST_Compile (in /usr/bin/python2.7)
==14093==    by 0x22C604: ??? (in /usr/bin/python2.7)
==14093==    by 0x2593D5: PyRun_StringFlags (in /usr/bin/python2.7)
==14093==    by 0x206A94: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x203C37: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x2035FD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x203231: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==  Address 0x62d1020 is 368 bytes inside a block of size 768 free'd
==14093==    at 0x4C31D2F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x22F589: ??? (in /usr/bin/python2.7)
==14093==    by 0x230648: ??? (in /usr/bin/python2.7)
==14093==    by 0x22CE86: ??? (in /usr/bin/python2.7)
==14093==    by 0x224B92: PyAST_Compile (in /usr/bin/python2.7)
==14093==    by 0x22C604: ??? (in /usr/bin/python2.7)
==14093==    by 0x2593D5: PyRun_StringFlags (in /usr/bin/python2.7)
==14093==    by 0x206A94: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x203C37: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x2035FD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==  Block was alloc'd at
==14093==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x15FB60: ??? (in /usr/bin/python2.7)
==14093==    by 0x22F589: ??? (in /usr/bin/python2.7)
==14093==    by 0x22DC25: ??? (in /usr/bin/python2.7)
==14093==    by 0x22D425: ??? (in /usr/bin/python2.7)
==14093==    by 0x23061B: ??? (in /usr/bin/python2.7)
==14093==    by 0x22CE64: ??? (in /usr/bin/python2.7)
==14093==    by 0x224B92: PyAST_Compile (in /usr/bin/python2.7)
==14093==    by 0x22C604: ??? (in /usr/bin/python2.7)
==14093==    by 0x2593D5: PyRun_StringFlags (in /usr/bin/python2.7)
==14093==    by 0x206A94: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x157BFF: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x1EB45A: ??? (in /usr/bin/python2.7)
==14093==    by 0x1FCCC2: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x203C37: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x2035FD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x203231: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x203231: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x1FB628: PyEval_EvalCode (in /usr/bin/python2.7)
==14093==    by 0x1FB564: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==14093==    by 0x1F4592: ??? (in /usr/bin/python2.7)
==14093==  Address 0x62c3020 is 1,920 bytes inside a block of size 4,097 free'd
==14093==    at 0x4C30D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1E5FB2: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==14093==    by 0x1E79E7: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E777D: PyObject_Call (in /usr/bin/python2.7)
==14093==    by 0x2077FF: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==14093==    by 0x200C09: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x1FB628: PyEval_EvalCode (in /usr/bin/python2.7)
==14093==    by 0x22C61E: ??? (in /usr/bin/python2.7)
==14093==    by 0x2593D5: PyRun_StringFlags (in /usr/bin/python2.7)
==14093==    by 0x206A94: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==  Block was alloc'd at
==14093==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1E5C57: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==14093==    by 0x1E79E7: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E777D: PyObject_Call (in /usr/bin/python2.7)
==14093==    by 0x2077FF: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==14093==    by 0x200C09: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x1FB628: PyEval_EvalCode (in /usr/bin/python2.7)
==14093==    by 0x22C61E: ??? (in /usr/bin/python2.7)
==14093==    by 0x2593D5: PyRun_StringFlags (in /usr/bin/python2.7)
==14093==    by 0x206A94: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x157BFF: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x2389F4: ??? (in /usr/bin/python2.7)
==14093==    by 0x238795: ??? (in /usr/bin/python2.7)
==14093==    by 0x224A9F: PyAST_Compile (in /usr/bin/python2.7)
==14093==    by 0x22C604: ??? (in /usr/bin/python2.7)
==14093==    by 0x2593D5: PyRun_StringFlags (in /usr/bin/python2.7)
==14093==    by 0x206A94: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x1FB628: PyEval_EvalCode (in /usr/bin/python2.7)
==14093==    by 0x22C61E: ??? (in /usr/bin/python2.7)
==14093==    by 0x2593D5: PyRun_StringFlags (in /usr/bin/python2.7)
==14093==    by 0x206A94: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==  Address 0x630a020 is 80 bytes inside a block of size 192 free'd
==14093==    at 0x4C30D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x23662A: PyCode_Optimize (in /usr/bin/python2.7)
==14093==    by 0x234862: ??? (in /usr/bin/python2.7)
==14093==    by 0x24E08E: ??? (in /usr/bin/python2.7)
==14093==    by 0x22D8C5: ??? (in /usr/bin/python2.7)
==14093==    by 0x22D185: ??? (in /usr/bin/python2.7)
==14093==    by 0x22D185: ??? (in /usr/bin/python2.7)
==14093==    by 0x22D185: ??? (in /usr/bin/python2.7)
==14093==    by 0x230709: ??? (in /usr/bin/python2.7)
==14093==    by 0x231B8C: ??? (in /usr/bin/python2.7)
==14093==    by 0x230976: ??? (in /usr/bin/python2.7)
==14093==    by 0x22CE42: ??? (in /usr/bin/python2.7)
==14093==  Block was alloc'd at
==14093==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x2362FD: PyCode_Optimize (in /usr/bin/python2.7)
==14093==    by 0x234862: ??? (in /usr/bin/python2.7)
==14093==    by 0x24E08E: ??? (in /usr/bin/python2.7)
==14093==    by 0x22D8C5: ??? (in /usr/bin/python2.7)
==14093==    by 0x22D185: ??? (in /usr/bin/python2.7)
==14093==    by 0x22D185: ??? (in /usr/bin/python2.7)
==14093==    by 0x22D185: ??? (in /usr/bin/python2.7)
==14093==    by 0x230709: ??? (in /usr/bin/python2.7)
==14093==    by 0x231B8C: ??? (in /usr/bin/python2.7)
==14093==    by 0x230976: ??? (in /usr/bin/python2.7)
==14093==    by 0x22CE42: ??? (in /usr/bin/python2.7)
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x157BFF: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x238989: ??? (in /usr/bin/python2.7)
==14093==    by 0x238795: ??? (in /usr/bin/python2.7)
==14093==    by 0x224A9F: PyAST_Compile (in /usr/bin/python2.7)
==14093==    by 0x22C604: ??? (in /usr/bin/python2.7)
==14093==    by 0x227321: PyRun_FileExFlags (in /usr/bin/python2.7)
==14093==    by 0x22667C: PyRun_SimpleFileExFlags (in /usr/bin/python2.7)
==14093==    by 0x1D51AA: Py_Main (in /usr/bin/python2.7)
==14093==    by 0x5064B96: (below main) (libc-start.c:310)
==14093==  Address 0x63e7020 is 16 bytes after a block of size 36,032 free'd
==14093==    at 0x4C30D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1F96DB: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F5B53: PyParser_ASTFromFile (in /usr/bin/python2.7)
==14093==    by 0x2272EB: PyRun_FileExFlags (in /usr/bin/python2.7)
==14093==    by 0x22667C: PyRun_SimpleFileExFlags (in /usr/bin/python2.7)
==14093==    by 0x1D51AA: Py_Main (in /usr/bin/python2.7)
==14093==    by 0x5064B96: (below main) (libc-start.c:310)
==14093==  Block was alloc'd at
==14093==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1F69EA: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F5B53: PyParser_ASTFromFile (in /usr/bin/python2.7)
==14093==    by 0x2272EB: PyRun_FileExFlags (in /usr/bin/python2.7)
==14093==    by 0x22667C: PyRun_SimpleFileExFlags (in /usr/bin/python2.7)
==14093==    by 0x1D51AA: Py_Main (in /usr/bin/python2.7)
==14093==    by 0x5064B96: (below main) (libc-start.c:310)
==14093== 
==14093== Syscall param sched_getaffinity(mask) points to unaddressable byte(s)
==14093==    at 0x5146F2F: sched_getaffinity@@GLIBC_2.3.4 (sched_getaffinity.c:36)
==14093==    by 0x7CB838B: get_num_procs (in /usr/local/lib/python2.7/dist-packages/numpy/.libs/libopenblasp-r0-8dca6697.3.0.dev.so)
==14093==    by 0x7CB847C: blas_get_cpu_number (in /usr/local/lib/python2.7/dist-packages/numpy/.libs/libopenblasp-r0-8dca6697.3.0.dev.so)
==14093==    by 0x7A90077: gotoblas_init (in /usr/local/lib/python2.7/dist-packages/numpy/.libs/libopenblasp-r0-8dca6697.3.0.dev.so)
==14093==    by 0x4010732: call_init (dl-init.c:72)
==14093==    by 0x4010732: _dl_init (dl-init.c:119)
==14093==    by 0x40151FE: dl_open_worker (dl-open.c:522)
==14093==    by 0x51AA2DE: _dl_catch_exception (dl-error-skeleton.c:196)
==14093==    by 0x40147C9: _dl_open (dl-open.c:605)
==14093==    by 0x5653F95: dlopen_doit (dlopen.c:66)
==14093==    by 0x51AA2DE: _dl_catch_exception (dl-error-skeleton.c:196)
==14093==    by 0x51AA36E: _dl_catch_error (dl-error-skeleton.c:215)
==14093==    by 0x5654734: _dlerror_run (dlerror.c:162)
==14093==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x157BFF: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x211FF5: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F45A7: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F5A68: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A56: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E5E10: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==14093==    by 0x1E79E7: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E777D: PyObject_Call (in /usr/bin/python2.7)
==14093==    by 0x2077FF: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==14093==    by 0x200C09: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x1FB628: PyEval_EvalCode (in /usr/bin/python2.7)
==14093==  Address 0x7303020 is 16,416 bytes inside a block of size 20,232 free'd
==14093==    at 0x4C30D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1F49ED: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==14093==    by 0x1F4930: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4548: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F5A68: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A56: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E5E10: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==14093==    by 0x1E79E7: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E777D: PyObject_Call (in /usr/bin/python2.7)
==14093==    by 0x2077FF: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==14093==    by 0x200C09: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==  Block was alloc'd at
==14093==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1F49B8: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==14093==    by 0x1F4930: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4548: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F5A68: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A56: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E5E10: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==14093==    by 0x1E79E7: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E777D: PyObject_Call (in /usr/bin/python2.7)
==14093==    by 0x2077FF: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==14093==    by 0x200C09: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093== 
==14093== Conditional jump or move depends on uninitialised value(s)
==14093==    at 0x15FB13: ??? (in /usr/bin/python2.7)
==14093==    by 0x240C2F: _PyObject_GC_Resize (in /usr/bin/python2.7)
==14093==    by 0x1FD943: PyFrame_New (in /usr/bin/python2.7)
==14093==    by 0x20316A: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x203231: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x203231: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x2035FD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x203C37: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x2035FD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093== 
==14093== Use of uninitialised value of size 8
==14093==    at 0x15FB20: ??? (in /usr/bin/python2.7)
==14093==    by 0x240C2F: _PyObject_GC_Resize (in /usr/bin/python2.7)
==14093==    by 0x1FD943: PyFrame_New (in /usr/bin/python2.7)
==14093==    by 0x20316A: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x203231: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x203231: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x2035FD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x203C37: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x2035FD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x157BFF: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x212203: ??? (in /usr/bin/python2.7)
==14093==    by 0x1EB16B: ??? (in /usr/bin/python2.7)
==14093==    by 0x212017: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F45A7: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A56: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E9EC2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E5EFD: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==14093==    by 0x1E79E7: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E777D: PyObject_Call (in /usr/bin/python2.7)
==14093==    by 0x2077FF: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==14093==    by 0x200C09: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==  Address 0x73d2020 is 48 bytes inside a block of size 64 free'd
==14093==    at 0x4C30D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1DCF74: ??? (in /usr/bin/python2.7)
==14093==    by 0x1FC3FA: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x2035FD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x203231: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x203231: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x203231: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x203231: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x2035FD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x203C37: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==  Block was alloc'd at
==14093==    at 0x4C31D2F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1D6C0F: ??? (in /usr/bin/python2.7)
==14093==    by 0x1D68B4: PyList_Append (in /usr/bin/python2.7)
==14093==    by 0x1FFA74: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x2035FD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x203231: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x2035FD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x203231: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x203231: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x203231: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x15FB0A: ??? (in /usr/bin/python2.7)
==14093==    by 0x2533D4: ??? (in /usr/bin/python2.7)
==14093==    by 0x25303C: ??? (in /usr/bin/python2.7)
==14093==    by 0x205FE4: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x2035FD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x1FB628: PyEval_EvalCode (in /usr/bin/python2.7)
==14093==    by 0x1FB564: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==14093==    by 0x1F4592: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A56: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E9EC2: ??? (in /usr/bin/python2.7)
==14093==  Address 0x125ee020 is 1,328 bytes inside a block of size 1,559 free'd
==14093==    at 0x4C31D2F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1EAF17: _PyString_Resize (in /usr/bin/python2.7)
==14093==    by 0x2544D2: ??? (in /usr/bin/python2.7)
==14093==    by 0x25303C: ??? (in /usr/bin/python2.7)
==14093==    by 0x205FE4: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x2035FD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x1FB628: PyEval_EvalCode (in /usr/bin/python2.7)
==14093==    by 0x1FB564: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==14093==    by 0x1F4592: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A56: ??? (in /usr/bin/python2.7)
==14093==  Block was alloc'd at
==14093==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1E1AB1: PyString_FromStringAndSize (in /usr/bin/python2.7)
==14093==    by 0x25309A: ??? (in /usr/bin/python2.7)
==14093==    by 0x25303C: ??? (in /usr/bin/python2.7)
==14093==    by 0x205FE4: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x2035FD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x1FB628: PyEval_EvalCode (in /usr/bin/python2.7)
==14093==    by 0x1FB564: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==14093==    by 0x1F4592: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A56: ??? (in /usr/bin/python2.7)
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x222E34: ??? (in /usr/bin/python2.7)
==14093==    by 0x259489: PyParser_ASTFromString (in /usr/bin/python2.7)
==14093==    by 0x2593B5: PyRun_StringFlags (in /usr/bin/python2.7)
==14093==    by 0x206A94: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x2035FD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x1FB628: PyEval_EvalCode (in /usr/bin/python2.7)
==14093==    by 0x1FB564: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==14093==    by 0x1F4592: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A56: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E9EC2: ??? (in /usr/bin/python2.7)
==14093==  Address 0x125fb020 is 35,248 bytes inside a block of size 36,032 free'd
==14093==    at 0x4C30D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1F96DB: ??? (in /usr/bin/python2.7)
==14093==    by 0x2594C9: PyParser_ASTFromString (in /usr/bin/python2.7)
==14093==    by 0x2593B5: PyRun_StringFlags (in /usr/bin/python2.7)
==14093==    by 0x206A94: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x2035FD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x1FB628: PyEval_EvalCode (in /usr/bin/python2.7)
==14093==    by 0x1FB564: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==14093==    by 0x1F4592: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A56: ??? (in /usr/bin/python2.7)
==14093==  Block was alloc'd at
==14093==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1F69EA: ??? (in /usr/bin/python2.7)
==14093==    by 0x2594C9: PyParser_ASTFromString (in /usr/bin/python2.7)
==14093==    by 0x2593B5: PyRun_StringFlags (in /usr/bin/python2.7)
==14093==    by 0x206A94: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x2035FD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x1FB628: PyEval_EvalCode (in /usr/bin/python2.7)
==14093==    by 0x1FB564: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==14093==    by 0x1F4592: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A56: ??? (in /usr/bin/python2.7)
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x157BFF: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x238989: ??? (in /usr/bin/python2.7)
==14093==    by 0x238795: ??? (in /usr/bin/python2.7)
==14093==    by 0x230A9A: ??? (in /usr/bin/python2.7)
==14093==    by 0x22CEA8: ??? (in /usr/bin/python2.7)
==14093==    by 0x230C2F: ??? (in /usr/bin/python2.7)
==14093==    by 0x22CE42: ??? (in /usr/bin/python2.7)
==14093==    by 0x224B92: PyAST_Compile (in /usr/bin/python2.7)
==14093==    by 0x22C604: ??? (in /usr/bin/python2.7)
==14093==    by 0x2593D5: PyRun_StringFlags (in /usr/bin/python2.7)
==14093==    by 0x206A94: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==  Address 0x12601020 is 32 bytes before a block of size 32 in arena "client"
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x15FB0A: ??? (in /usr/bin/python2.7)
==14093==    by 0x22F589: ??? (in /usr/bin/python2.7)
==14093==    by 0x2391DD: ??? (in /usr/bin/python2.7)
==14093==    by 0x230ABE: ??? (in /usr/bin/python2.7)
==14093==    by 0x22CF1D: ??? (in /usr/bin/python2.7)
==14093==    by 0x230C2F: ??? (in /usr/bin/python2.7)
==14093==    by 0x22CE42: ??? (in /usr/bin/python2.7)
==14093==    by 0x224B92: PyAST_Compile (in /usr/bin/python2.7)
==14093==    by 0x22C604: ??? (in /usr/bin/python2.7)
==14093==    by 0x2593D5: PyRun_StringFlags (in /usr/bin/python2.7)
==14093==    by 0x206A94: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==  Address 0x12601020 is 32 bytes before a block of size 32 in arena "client"
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x15FB0A: ??? (in /usr/bin/python2.7)
==14093==    by 0x22F589: ??? (in /usr/bin/python2.7)
==14093==    by 0x230648: ??? (in /usr/bin/python2.7)
==14093==    by 0x22CF1D: ??? (in /usr/bin/python2.7)
==14093==    by 0x230C2F: ??? (in /usr/bin/python2.7)
==14093==    by 0x22CE42: ??? (in /usr/bin/python2.7)
==14093==    by 0x224B92: PyAST_Compile (in /usr/bin/python2.7)
==14093==    by 0x22C604: ??? (in /usr/bin/python2.7)
==14093==    by 0x2593D5: PyRun_StringFlags (in /usr/bin/python2.7)
==14093==    by 0x206A94: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x2035FD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==  Address 0x12603020 is 48 bytes inside a block of size 74 free'd
==14093==    at 0x4C30D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x236632: PyCode_Optimize (in /usr/bin/python2.7)
==14093==    by 0x234862: ??? (in /usr/bin/python2.7)
==14093==    by 0x230A8F: ??? (in /usr/bin/python2.7)
==14093==    by 0x22CF02: ??? (in /usr/bin/python2.7)
==14093==    by 0x230C2F: ??? (in /usr/bin/python2.7)
==14093==    by 0x22CE42: ??? (in /usr/bin/python2.7)
==14093==    by 0x224B92: PyAST_Compile (in /usr/bin/python2.7)
==14093==    by 0x22C604: ??? (in /usr/bin/python2.7)
==14093==    by 0x2593D5: PyRun_StringFlags (in /usr/bin/python2.7)
==14093==    by 0x206A94: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==  Block was alloc'd at
==14093==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x2362B0: PyCode_Optimize (in /usr/bin/python2.7)
==14093==    by 0x234862: ??? (in /usr/bin/python2.7)
==14093==    by 0x230A8F: ??? (in /usr/bin/python2.7)
==14093==    by 0x22CF02: ??? (in /usr/bin/python2.7)
==14093==    by 0x230C2F: ??? (in /usr/bin/python2.7)
==14093==    by 0x22CE42: ??? (in /usr/bin/python2.7)
==14093==    by 0x224B92: PyAST_Compile (in /usr/bin/python2.7)
==14093==    by 0x22C604: ??? (in /usr/bin/python2.7)
==14093==    by 0x2593D5: PyRun_StringFlags (in /usr/bin/python2.7)
==14093==    by 0x206A94: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x157BFF: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x238962: ??? (in /usr/bin/python2.7)
==14093==    by 0x238795: ??? (in /usr/bin/python2.7)
==14093==    by 0x230C79: ??? (in /usr/bin/python2.7)
==14093==    by 0x22CE42: ??? (in /usr/bin/python2.7)
==14093==    by 0x224B92: PyAST_Compile (in /usr/bin/python2.7)
==14093==    by 0x22C604: ??? (in /usr/bin/python2.7)
==14093==    by 0x2593D5: PyRun_StringFlags (in /usr/bin/python2.7)
==14093==    by 0x206A94: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x2035FD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==  Address 0x12603020 is 48 bytes inside a block of size 74 free'd
==14093==    at 0x4C30D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x236632: PyCode_Optimize (in /usr/bin/python2.7)
==14093==    by 0x234862: ??? (in /usr/bin/python2.7)
==14093==    by 0x230A8F: ??? (in /usr/bin/python2.7)
==14093==    by 0x22CF02: ??? (in /usr/bin/python2.7)
==14093==    by 0x230C2F: ??? (in /usr/bin/python2.7)
==14093==    by 0x22CE42: ??? (in /usr/bin/python2.7)
==14093==    by 0x224B92: PyAST_Compile (in /usr/bin/python2.7)
==14093==    by 0x22C604: ??? (in /usr/bin/python2.7)
==14093==    by 0x2593D5: PyRun_StringFlags (in /usr/bin/python2.7)
==14093==    by 0x206A94: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==  Block was alloc'd at
==14093==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x2362B0: PyCode_Optimize (in /usr/bin/python2.7)
==14093==    by 0x234862: ??? (in /usr/bin/python2.7)
==14093==    by 0x230A8F: ??? (in /usr/bin/python2.7)
==14093==    by 0x22CF02: ??? (in /usr/bin/python2.7)
==14093==    by 0x230C2F: ??? (in /usr/bin/python2.7)
==14093==    by 0x22CE42: ??? (in /usr/bin/python2.7)
==14093==    by 0x224B92: PyAST_Compile (in /usr/bin/python2.7)
==14093==    by 0x22C604: ??? (in /usr/bin/python2.7)
==14093==    by 0x2593D5: PyRun_StringFlags (in /usr/bin/python2.7)
==14093==    by 0x206A94: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x157BFF: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x1FC3FA: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x2035FD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x1FB628: PyEval_EvalCode (in /usr/bin/python2.7)
==14093==    by 0x1FB564: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==14093==    by 0x1F4592: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A56: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E9EC2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E5EFD: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==14093==    by 0x1E79E7: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E777D: PyObject_Call (in /usr/bin/python2.7)
==14093==  Address 0x125ee020 is 1,328 bytes inside a block of size 1,559 free'd
==14093==    at 0x4C31D2F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1EAF17: _PyString_Resize (in /usr/bin/python2.7)
==14093==    by 0x2544D2: ??? (in /usr/bin/python2.7)
==14093==    by 0x25303C: ??? (in /usr/bin/python2.7)
==14093==    by 0x205FE4: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x2035FD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x1FB628: PyEval_EvalCode (in /usr/bin/python2.7)
==14093==    by 0x1FB564: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==14093==    by 0x1F4592: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A56: ??? (in /usr/bin/python2.7)
==14093==  Block was alloc'd at
==14093==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1E1AB1: PyString_FromStringAndSize (in /usr/bin/python2.7)
==14093==    by 0x25309A: ??? (in /usr/bin/python2.7)
==14093==    by 0x25303C: ??? (in /usr/bin/python2.7)
==14093==    by 0x205FE4: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x2035FD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x1FB628: PyEval_EvalCode (in /usr/bin/python2.7)
==14093==    by 0x1FB564: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==14093==    by 0x1F4592: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A56: ??? (in /usr/bin/python2.7)
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x15FB0A: ??? (in /usr/bin/python2.7)
==14093==    by 0x1EAF17: _PyString_Resize (in /usr/bin/python2.7)
==14093==    by 0x2544D2: ??? (in /usr/bin/python2.7)
==14093==    by 0x25303C: ??? (in /usr/bin/python2.7)
==14093==    by 0x205FE4: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x2035FD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x1FB628: PyEval_EvalCode (in /usr/bin/python2.7)
==14093==    by 0x1FB564: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==14093==    by 0x1F4592: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A56: ??? (in /usr/bin/python2.7)
==14093==  Address 0x1264f020 is 2,816 bytes inside a block of size 4,097 free'd
==14093==    at 0x4C30D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1E5F0D: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==14093==    by 0x1E79E7: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E777D: PyObject_Call (in /usr/bin/python2.7)
==14093==    by 0x2077FF: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==14093==    by 0x200C09: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x1FB628: PyEval_EvalCode (in /usr/bin/python2.7)
==14093==    by 0x1FB564: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==14093==    by 0x1F4592: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A56: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6250: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==14093==  Block was alloc'd at
==14093==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1E5C57: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==14093==    by 0x1E79E7: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E777D: PyObject_Call (in /usr/bin/python2.7)
==14093==    by 0x2077FF: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==14093==    by 0x200C09: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x1FB628: PyEval_EvalCode (in /usr/bin/python2.7)
==14093==    by 0x1FB564: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==14093==    by 0x1F4592: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A56: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6250: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x15FB0A: ??? (in /usr/bin/python2.7)
==14093==    by 0x240C2F: _PyObject_GC_Resize (in /usr/bin/python2.7)
==14093==    by 0x1FD943: PyFrame_New (in /usr/bin/python2.7)
==14093==    by 0x20316A: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x203231: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x203231: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x203231: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x2035FD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x203C37: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==  Address 0x73ce020 is 384 bytes inside a block of size 744 free'd
==14093==    at 0x4C30D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x212203: ??? (in /usr/bin/python2.7)
==14093==    by 0x1EB16B: ??? (in /usr/bin/python2.7)
==14093==    by 0x212017: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F45A7: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A56: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E9EC2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E5EFD: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==14093==    by 0x1E79E7: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E777D: PyObject_Call (in /usr/bin/python2.7)
==14093==    by 0x2077FF: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==14093==    by 0x200C09: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==  Block was alloc'd at
==14093==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x156CE8: _PyObject_GC_Malloc (in /usr/bin/python2.7)
==14093==    by 0x1FD98D: PyFrame_New (in /usr/bin/python2.7)
==14093==    by 0x20316A: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x203231: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x203231: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x203231: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x2035FD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x2035FD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093== 
==14093== Conditional jump or move depends on uninitialised value(s)
==14093==    at 0x157C08: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x212203: ??? (in /usr/bin/python2.7)
==14093==    by 0x1EB16B: ??? (in /usr/bin/python2.7)
==14093==    by 0x212017: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F45A7: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A56: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6250: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==14093==    by 0x1E79E7: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E777D: PyObject_Call (in /usr/bin/python2.7)
==14093==    by 0x2077FF: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==14093==    by 0x200C09: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093== 
==14093== Use of uninitialised value of size 8
==14093==    at 0x157C1C: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x212203: ??? (in /usr/bin/python2.7)
==14093==    by 0x1EB16B: ??? (in /usr/bin/python2.7)
==14093==    by 0x212017: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F45A7: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A56: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6250: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==14093==    by 0x1E79E7: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E777D: PyObject_Call (in /usr/bin/python2.7)
==14093==    by 0x2077FF: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==14093==    by 0x200C09: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x157BFF: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x1EB285: ??? (in /usr/bin/python2.7)
==14093==    by 0x212017: ??? (in /usr/bin/python2.7)
==14093==    by 0x1EB16B: ??? (in /usr/bin/python2.7)
==14093==    by 0x212017: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F45A7: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A56: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E5E10: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==14093==    by 0x1E79E7: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E777D: PyObject_Call (in /usr/bin/python2.7)
==14093==    by 0x2077FF: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==14093==    by 0x200C09: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==  Address 0x1261c020 is 368 bytes inside a block of size 576 free'd
==14093==    at 0x4C31D2F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1D6C71: ??? (in /usr/bin/python2.7)
==14093==    by 0x1D68B4: PyList_Append (in /usr/bin/python2.7)
==14093==    by 0x1F4BAD: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EF8: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EE2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EE2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4A35: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==14093==    by 0x1F49E2: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==14093==  Block was alloc'd at
==14093==    at 0x4C31D2F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1D6C71: ??? (in /usr/bin/python2.7)
==14093==    by 0x1D68B4: PyList_Append (in /usr/bin/python2.7)
==14093==    by 0x1F4BAD: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D18: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4F0C: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D38: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EE2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EE2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4A35: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==14093==    by 0x1F49E2: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x157BFF: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x1EB285: ??? (in /usr/bin/python2.7)
==14093==    by 0x21203A: ??? (in /usr/bin/python2.7)
==14093==    by 0x1EB16B: ??? (in /usr/bin/python2.7)
==14093==    by 0x212017: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F45A7: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A56: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E5E10: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==14093==    by 0x1E79E7: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E777D: PyObject_Call (in /usr/bin/python2.7)
==14093==    by 0x2077FF: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==14093==    by 0x200C09: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==  Address 0x12621020 is 2,000 bytes inside a block of size 2,152 free'd
==14093==    at 0x4C31D2F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1D6C71: ??? (in /usr/bin/python2.7)
==14093==    by 0x1D68B4: PyList_Append (in /usr/bin/python2.7)
==14093==    by 0x1F4BAD: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D18: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EF8: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EE2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EE2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4A35: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==14093==    by 0x1F49E2: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==14093==  Block was alloc'd at
==14093==    at 0x4C31D2F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1D6C71: ??? (in /usr/bin/python2.7)
==14093==    by 0x1D68B4: PyList_Append (in /usr/bin/python2.7)
==14093==    by 0x1F4BAD: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4CD0: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4F0C: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EE2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EE2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EE2: ??? (in /usr/bin/python2.7)
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x157BFF: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x212203: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F45A7: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F5A68: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A56: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E5E10: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==14093==    by 0x1E79E7: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E777D: PyObject_Call (in /usr/bin/python2.7)
==14093==    by 0x2077FF: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==14093==    by 0x200C09: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x1FB628: PyEval_EvalCode (in /usr/bin/python2.7)
==14093==  Address 0x125bd020 is 0 bytes after a block of size 368 free'd
==14093==    at 0x4C30D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1DCF74: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4A4F: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==14093==    by 0x1F49E2: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==14093==    by 0x1F4930: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4548: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F5A68: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A56: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E5E10: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==14093==    by 0x1E79E7: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E777D: PyObject_Call (in /usr/bin/python2.7)
==14093==    by 0x2077FF: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==14093==  Block was alloc'd at
==14093==    at 0x4C31D2F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1D6C71: ??? (in /usr/bin/python2.7)
==14093==    by 0x1D68B4: PyList_Append (in /usr/bin/python2.7)
==14093==    by 0x1F4BAD: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4F61: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4A35: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==14093==    by 0x1F49E2: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==14093==    by 0x1F4930: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4548: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F5A68: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A56: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E5E10: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x157BFF: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x1EB16B: ??? (in /usr/bin/python2.7)
==14093==    by 0x20344C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x2035FD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x217618: ??? (in /usr/bin/python2.7)
==14093==    by 0x2300DD: ??? (in /usr/bin/python2.7)
==14093==    by 0x22FCE9: ??? (in /usr/bin/python2.7)
==14093==    by 0x1EC86A: ??? (in /usr/bin/python2.7)
==14093==    by 0x20341F: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==  Address 0x12d34020 is 1,952 bytes inside a block of size 2,537 free'd
==14093==    at 0x4C30D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1EB16B: ??? (in /usr/bin/python2.7)
==14093==    by 0x1FE4E2: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x2035FD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x217618: ??? (in /usr/bin/python2.7)
==14093==    by 0x2300DD: ??? (in /usr/bin/python2.7)
==14093==    by 0x22FCE9: ??? (in /usr/bin/python2.7)
==14093==    by 0x1EC86A: ??? (in /usr/bin/python2.7)
==14093==    by 0x20341F: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==  Block was alloc'd at
==14093==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1E1AB1: PyString_FromStringAndSize (in /usr/bin/python2.7)
==14093==    by 0x26F233: ??? (in /usr/bin/python2.7)
==14093==    by 0x1FE4C9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x2035FD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x217618: ??? (in /usr/bin/python2.7)
==14093==    by 0x2300DD: ??? (in /usr/bin/python2.7)
==14093==    by 0x22FCE9: ??? (in /usr/bin/python2.7)
==14093==    by 0x1EC86A: ??? (in /usr/bin/python2.7)
==14093==    by 0x20341F: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x157BFF: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x281C0E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1FE4C9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x2035FD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x217618: ??? (in /usr/bin/python2.7)
==14093==    by 0x2300DD: ??? (in /usr/bin/python2.7)
==14093==    by 0x22FCE9: ??? (in /usr/bin/python2.7)
==14093==    by 0x1EC86A: ??? (in /usr/bin/python2.7)
==14093==    by 0x20341F: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==  Address 0x12d37020 is 784 bytes inside a block of size 2,688 free'd
==14093==    at 0x4C30D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x281C0E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1FE4C9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x2035FD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x217618: ??? (in /usr/bin/python2.7)
==14093==    by 0x2300DD: ??? (in /usr/bin/python2.7)
==14093==    by 0x22FCE9: ??? (in /usr/bin/python2.7)
==14093==    by 0x1EC86A: ??? (in /usr/bin/python2.7)
==14093==    by 0x20341F: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==  Block was alloc'd at
==14093==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x28540A: ??? (in /usr/bin/python2.7)
==14093==    by 0x240CAD: ??? (in /usr/bin/python2.7)
==14093==    by 0x281BD1: ??? (in /usr/bin/python2.7)
==14093==    by 0x1FE4C9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x2035FD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x217618: ??? (in /usr/bin/python2.7)
==14093==    by 0x2300DD: ??? (in /usr/bin/python2.7)
==14093==    by 0x22FCE9: ??? (in /usr/bin/python2.7)
==14093==    by 0x1EC86A: ??? (in /usr/bin/python2.7)
==14093== 
==14093== Conditional jump or move depends on uninitialised value(s)
==14093==    at 0x157C08: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x281C0E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1FE4C9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x2035FD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x217618: ??? (in /usr/bin/python2.7)
==14093==    by 0x2300DD: ??? (in /usr/bin/python2.7)
==14093==    by 0x22FCE9: ??? (in /usr/bin/python2.7)
==14093==    by 0x1EC86A: ??? (in /usr/bin/python2.7)
==14093==    by 0x20341F: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093== 
==14093== Use of uninitialised value of size 8
==14093==    at 0x157C1C: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x281C0E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1FE4C9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x2035FD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x217618: ??? (in /usr/bin/python2.7)
==14093==    by 0x2300DD: ??? (in /usr/bin/python2.7)
==14093==    by 0x22FCE9: ??? (in /usr/bin/python2.7)
==14093==    by 0x1EC86A: ??? (in /usr/bin/python2.7)
==14093==    by 0x20341F: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x23D805: ??? (in /usr/bin/python2.7)
==14093==    by 0x1FC3FA: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x2035FD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x217618: ??? (in /usr/bin/python2.7)
==14093==    by 0x2300DD: ??? (in /usr/bin/python2.7)
==14093==    by 0x22FCE9: ??? (in /usr/bin/python2.7)
==14093==    by 0x1EC86A: ??? (in /usr/bin/python2.7)
==14093==    by 0x20341F: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x1FB628: PyEval_EvalCode (in /usr/bin/python2.7)
==14093==    by 0x1FB564: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==14093==  Address 0x12d35020 is 3,344 bytes inside a block of size 5,037 free'd
==14093==    at 0x4C30D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1EB16B: ??? (in /usr/bin/python2.7)
==14093==    by 0x20344C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x2035FD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x217618: ??? (in /usr/bin/python2.7)
==14093==    by 0x2300DD: ??? (in /usr/bin/python2.7)
==14093==    by 0x22FCE9: ??? (in /usr/bin/python2.7)
==14093==    by 0x1EC86A: ??? (in /usr/bin/python2.7)
==14093==    by 0x20341F: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==  Block was alloc'd at
==14093==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1E1AB1: PyString_FromStringAndSize (in /usr/bin/python2.7)
==14093==    by 0x28249F: ??? (in /usr/bin/python2.7)
==14093==    by 0x1FE4C9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x2035FD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x217618: ??? (in /usr/bin/python2.7)
==14093==    by 0x2300DD: ??? (in /usr/bin/python2.7)
==14093==    by 0x22FCE9: ??? (in /usr/bin/python2.7)
==14093==    by 0x1EC86A: ??? (in /usr/bin/python2.7)
==14093==    by 0x20341F: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x157BFF: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x1EB16B: ??? (in /usr/bin/python2.7)
==14093==    by 0x212017: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F45A7: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F5A68: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A56: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E61C6: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==14093==    by 0x1E79E7: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E777D: PyObject_Call (in /usr/bin/python2.7)
==14093==    by 0x2077FF: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==14093==    by 0x200C09: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==  Address 0x12fae020 is 3,024 bytes inside a block of size 4,096 free'd
==14093==    at 0x4C30D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x50D12EA: _IO_setb (genops.c:349)
==14093==    by 0x50CF26B: _IO_file_close_it@@GLIBC_2.2.5 (fileops.c:154)
==14093==    by 0x50C1386: fclose@@GLIBC_2.2.5 (iofclose.c:53)
==14093==    by 0x1F4553: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F5A68: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A56: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E61C6: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==14093==    by 0x1E79E7: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E777D: PyObject_Call (in /usr/bin/python2.7)
==14093==    by 0x2077FF: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==14093==    by 0x200C09: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==  Block was alloc'd at
==14093==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x50C118B: _IO_file_doallocate (filedoalloc.c:101)
==14093==    by 0x50D1378: _IO_doallocbuf (genops.c:365)
==14093==    by 0x50D0253: _IO_file_underflow@@GLIBC_2.2.5 (fileops.c:495)
==14093==    by 0x50D13F1: _IO_default_uflow (genops.c:380)
==14093==    by 0x50CAE97: getc (getc.c:40)
==14093==    by 0x1F47C8: PyMarshal_ReadLongFromFile (in /usr/bin/python2.7)
==14093==    by 0x1F4510: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F5A68: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A56: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E61C6: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==14093==    by 0x1E79E7: ??? (in /usr/bin/python2.7)
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x157BFF: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x1EB16B: ??? (in /usr/bin/python2.7)
==14093==    by 0x1FE597: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x1FB628: PyEval_EvalCode (in /usr/bin/python2.7)
==14093==    by 0x1FB564: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==14093==    by 0x1F4592: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A56: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E9EC2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E5EFD: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==14093==    by 0x1E79E7: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E777D: PyObject_Call (in /usr/bin/python2.7)
==14093==  Address 0x13ef6020 is 2,432 bytes inside a block of size 4,097 free'd
==14093==    at 0x4C30D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1E5F0D: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==14093==    by 0x1E79E7: ??? (in /usr/bin/python2.7)
==14093==    by 0x1FE4C9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x203C37: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x1FB628: PyEval_EvalCode (in /usr/bin/python2.7)
==14093==    by 0x1FB564: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==14093==    by 0x1F4592: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A56: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E9EC2: ??? (in /usr/bin/python2.7)
==14093==  Block was alloc'd at
==14093==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1E5C57: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==14093==    by 0x1E79E7: ??? (in /usr/bin/python2.7)
==14093==    by 0x1FE4C9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x203C37: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x1FB628: PyEval_EvalCode (in /usr/bin/python2.7)
==14093==    by 0x1FB564: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==14093==    by 0x1F4592: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A56: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E9EC2: ??? (in /usr/bin/python2.7)
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x15FB0A: ??? (in /usr/bin/python2.7)
==14093==    by 0x1EA774: PyString_FromFormatV (in /usr/bin/python2.7)
==14093==    by 0x24DC28: PyString_FromFormat (in /usr/bin/python2.7)
==14093==    by 0xFC94840: ??? (in /usr/local/lib/python2.7/dist-packages/numpy/core/umath.so)
==14093==    by 0x2133A8: ??? (in /usr/bin/python2.7)
==14093==    by 0x15B161: _PyObject_GenericGetAttrWithDict (in /usr/bin/python2.7)
==14093==    by 0x1FE5CF: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x203C37: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x217618: ??? (in /usr/bin/python2.7)
==14093==    by 0x2300DD: ??? (in /usr/bin/python2.7)
==14093==  Address 0x149c8020 is 16 bytes after a block of size 528 in arena "client"
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x157BFF: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0xFC9484B: ??? (in /usr/local/lib/python2.7/dist-packages/numpy/core/umath.so)
==14093==    by 0x2133A8: ??? (in /usr/bin/python2.7)
==14093==    by 0x15B161: _PyObject_GenericGetAttrWithDict (in /usr/bin/python2.7)
==14093==    by 0x1FE5CF: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x203C37: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x217618: ??? (in /usr/bin/python2.7)
==14093==    by 0x2300DD: ??? (in /usr/bin/python2.7)
==14093==    by 0x22FCE9: ??? (in /usr/bin/python2.7)
==14093==    by 0x1EC86A: ??? (in /usr/bin/python2.7)
==14093==  Address 0x149c8020 is 16 bytes after a block of size 528 in arena "client"
==14093== 
==14093== Conditional jump or move depends on uninitialised value(s)
==14093==    at 0x15FB13: ??? (in /usr/bin/python2.7)
==14093==    by 0x1EA774: PyString_FromFormatV (in /usr/bin/python2.7)
==14093==    by 0x24DC28: PyString_FromFormat (in /usr/bin/python2.7)
==14093==    by 0xFC94840: ??? (in /usr/local/lib/python2.7/dist-packages/numpy/core/umath.so)
==14093==    by 0x2133A8: ??? (in /usr/bin/python2.7)
==14093==    by 0x15B161: _PyObject_GenericGetAttrWithDict (in /usr/bin/python2.7)
==14093==    by 0x1FE5CF: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x203C37: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x217618: ??? (in /usr/bin/python2.7)
==14093==    by 0x2300DD: ??? (in /usr/bin/python2.7)
==14093== 
==14093== Use of uninitialised value of size 8
==14093==    at 0x15FB20: ??? (in /usr/bin/python2.7)
==14093==    by 0x1EA774: PyString_FromFormatV (in /usr/bin/python2.7)
==14093==    by 0x24DC28: PyString_FromFormat (in /usr/bin/python2.7)
==14093==    by 0xFC94840: ??? (in /usr/local/lib/python2.7/dist-packages/numpy/core/umath.so)
==14093==    by 0x2133A8: ??? (in /usr/bin/python2.7)
==14093==    by 0x15B161: _PyObject_GenericGetAttrWithDict (in /usr/bin/python2.7)
==14093==    by 0x1FE5CF: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x203C37: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x217618: ??? (in /usr/bin/python2.7)
==14093==    by 0x2300DD: ??? (in /usr/bin/python2.7)
==14093== 
==14093== Conditional jump or move depends on uninitialised value(s)
==14093==    at 0x157C08: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0xFC9484B: ??? (in /usr/local/lib/python2.7/dist-packages/numpy/core/umath.so)
==14093==    by 0x2133A8: ??? (in /usr/bin/python2.7)
==14093==    by 0x15B161: _PyObject_GenericGetAttrWithDict (in /usr/bin/python2.7)
==14093==    by 0x1FE5CF: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x203C37: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x217618: ??? (in /usr/bin/python2.7)
==14093==    by 0x2300DD: ??? (in /usr/bin/python2.7)
==14093==    by 0x22FCE9: ??? (in /usr/bin/python2.7)
==14093==    by 0x1EC86A: ??? (in /usr/bin/python2.7)
==14093== 
==14093== Use of uninitialised value of size 8
==14093==    at 0x157C1C: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0xFC9484B: ??? (in /usr/local/lib/python2.7/dist-packages/numpy/core/umath.so)
==14093==    by 0x2133A8: ??? (in /usr/bin/python2.7)
==14093==    by 0x15B161: _PyObject_GenericGetAttrWithDict (in /usr/bin/python2.7)
==14093==    by 0x1FE5CF: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x203C37: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x217618: ??? (in /usr/bin/python2.7)
==14093==    by 0x2300DD: ??? (in /usr/bin/python2.7)
==14093==    by 0x22FCE9: ??? (in /usr/bin/python2.7)
==14093==    by 0x1EC86A: ??? (in /usr/bin/python2.7)
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x157BFF: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x238094: ??? (in /usr/bin/python2.7)
==14093==    by 0x1D7700: PyDict_SetItem (in /usr/bin/python2.7)
==14093==    by 0x2002C1: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x1FB628: PyEval_EvalCode (in /usr/bin/python2.7)
==14093==    by 0x1FB564: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==14093==    by 0x1F4592: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A56: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E9EC2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E5EFD: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==14093==    by 0x1E79E7: ??? (in /usr/bin/python2.7)
==14093==  Address 0x149ce020 is 1,232 bytes inside a block of size 1,694 free'd
==14093==    at 0x4C31D2F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1EA774: PyString_FromFormatV (in /usr/bin/python2.7)
==14093==    by 0x24DC28: PyString_FromFormat (in /usr/bin/python2.7)
==14093==    by 0xFC94840: ??? (in /usr/local/lib/python2.7/dist-packages/numpy/core/umath.so)
==14093==    by 0x2133A8: ??? (in /usr/bin/python2.7)
==14093==    by 0x15B161: _PyObject_GenericGetAttrWithDict (in /usr/bin/python2.7)
==14093==    by 0x1FE5CF: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x203C37: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x217618: ??? (in /usr/bin/python2.7)
==14093==    by 0x2300DD: ??? (in /usr/bin/python2.7)
==14093==  Block was alloc'd at
==14093==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1E1AB1: PyString_FromStringAndSize (in /usr/bin/python2.7)
==14093==    by 0x1EA499: PyString_FromFormatV (in /usr/bin/python2.7)
==14093==    by 0x24DC28: PyString_FromFormat (in /usr/bin/python2.7)
==14093==    by 0xFC94840: ??? (in /usr/local/lib/python2.7/dist-packages/numpy/core/umath.so)
==14093==    by 0x2133A8: ??? (in /usr/bin/python2.7)
==14093==    by 0x15B161: _PyObject_GenericGetAttrWithDict (in /usr/bin/python2.7)
==14093==    by 0x1FE5CF: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x203C37: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x217618: ??? (in /usr/bin/python2.7)
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x15FB0A: ??? (in /usr/bin/python2.7)
==14093==    by 0x1EAF17: _PyString_Resize (in /usr/bin/python2.7)
==14093==    by 0x2497A1: PyString_Format (in /usr/bin/python2.7)
==14093==    by 0x1FFCC2: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x203C37: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x217618: ??? (in /usr/bin/python2.7)
==14093==    by 0x2300DD: ??? (in /usr/bin/python2.7)
==14093==    by 0x22FCE9: ??? (in /usr/bin/python2.7)
==14093==    by 0x1EC86A: ??? (in /usr/bin/python2.7)
==14093==    by 0x20341F: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==  Address 0x14a32020 is 0 bytes inside a block of size 16 free'd
==14093==    at 0x4C30D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1DCF74: ??? (in /usr/bin/python2.7)
==14093==    by 0x203A93: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x2035FD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x217618: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E777D: PyObject_Call (in /usr/bin/python2.7)
==14093==    by 0x200A20: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x203C37: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==  Block was alloc'd at
==14093==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1D5798: PyList_New (in /usr/bin/python2.7)
==14093==    by 0x1FF509: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x2035FD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x217618: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E777D: PyObject_Call (in /usr/bin/python2.7)
==14093==    by 0x200A20: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x203C37: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x157BFF: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x1DCF67: ??? (in /usr/bin/python2.7)
==14093==    by 0x1FC3FA: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x203C37: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x1FB628: PyEval_EvalCode (in /usr/bin/python2.7)
==14093==    by 0x1FB564: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==14093==    by 0x1F4592: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A56: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E9EC2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E5EFD: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==14093==    by 0x1E79E7: ??? (in /usr/bin/python2.7)
==14093==  Address 0x14a47020 is 16 bytes before a block of size 8 free'd
==14093==    at 0x4C30D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1DCF74: ??? (in /usr/bin/python2.7)
==14093==    by 0x203E18: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x2035FD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x203C37: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x2035FD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x203C37: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==  Block was alloc'd at
==14093==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1D5798: PyList_New (in /usr/bin/python2.7)
==14093==    by 0x1FF509: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x2035FD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x203C37: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x2035FD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x203C37: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093== 
Traceback (most recent call last):
  File "toy.py", line 1, in <module>
    from corels import CorelsClassifier
  File "/usr/local/lib/python2.7/dist-packages/corels/__init__.py", line 1, in <module>
    from .corels import CorelsClassifier
  File "/usr/local/lib/python2.7/dist-packages/corels/corels.py", line 2, in <module>
    from . import _corels
  File "__init__.pxd", line 918, in init corels._corels
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject
==14093== Invalid read of size 4
==14093==    at 0x157BFF: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x1EB16B: ??? (in /usr/bin/python2.7)
==14093==    by 0x212017: ??? (in /usr/bin/python2.7)
==14093==    by 0x1EB16B: ??? (in /usr/bin/python2.7)
==14093==    by 0x212017: ??? (in /usr/bin/python2.7)
==14093==    by 0x1EB16B: ??? (in /usr/bin/python2.7)
==14093==    by 0x212017: ??? (in /usr/bin/python2.7)
==14093==    by 0x211D31: ??? (in /usr/bin/python2.7)
==14093==    by 0x218377: ??? (in /usr/bin/python2.7)
==14093==    by 0x218355: ??? (in /usr/bin/python2.7)
==14093==    by 0x218355: ??? (in /usr/bin/python2.7)
==14093==    by 0x1D7700: PyDict_SetItem (in /usr/bin/python2.7)
==14093==  Address 0x6400020 is 368 bytes inside a block of size 464 free'd
==14093==    at 0x4C31D2F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1D6C71: ??? (in /usr/bin/python2.7)
==14093==    by 0x1D68B4: PyList_Append (in /usr/bin/python2.7)
==14093==    by 0x1F4BAD: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EF8: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EE2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EE2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4A35: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==14093==    by 0x1F49E2: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==14093==  Block was alloc'd at
==14093==    at 0x4C31D2F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1D6C71: ??? (in /usr/bin/python2.7)
==14093==    by 0x1D68B4: PyList_Append (in /usr/bin/python2.7)
==14093==    by 0x1F4BAD: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EE2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EE2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EE2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4A35: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==14093==    by 0x1F49E2: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x157BFF: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x23CFB4: _PyModule_Clear (in /usr/bin/python2.7)
==14093==    by 0x23C6E3: PyImport_Cleanup (in /usr/bin/python2.7)
==14093==    by 0x239927: Py_Finalize (in /usr/bin/python2.7)
==14093==    by 0x1D5073: Py_Main (in /usr/bin/python2.7)
==14093==    by 0x5064B96: (below main) (libc-start.c:310)
==14093==  Address 0x127bc020 is 352 bytes inside a block of size 712 free'd
==14093==    at 0x4C30D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x211FF5: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F45A7: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A56: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E5E10: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==14093==    by 0x1E79E7: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E777D: PyObject_Call (in /usr/bin/python2.7)
==14093==    by 0x2077FF: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==14093==    by 0x200C09: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x1FB628: PyEval_EvalCode (in /usr/bin/python2.7)
==14093==    by 0x1FB564: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==14093==  Block was alloc'd at
==14093==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1E1AB1: PyString_FromStringAndSize (in /usr/bin/python2.7)
==14093==    by 0x1F4B40: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4ECC: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4A35: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==14093==    by 0x1F49E2: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==14093==    by 0x1F4930: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4548: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A56: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E5E10: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==14093==    by 0x1E79E7: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E777D: PyObject_Call (in /usr/bin/python2.7)
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x157BFF: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x211FF5: ??? (in /usr/bin/python2.7)
==14093==    by 0x211E1B: ??? (in /usr/bin/python2.7)
==14093==    by 0x1D7700: PyDict_SetItem (in /usr/bin/python2.7)
==14093==    by 0x23CB56: _PyModule_Clear (in /usr/bin/python2.7)
==14093==    by 0x23C6E3: PyImport_Cleanup (in /usr/bin/python2.7)
==14093==    by 0x239927: Py_Finalize (in /usr/bin/python2.7)
==14093==    by 0x1D5073: Py_Main (in /usr/bin/python2.7)
==14093==    by 0x5064B96: (below main) (libc-start.c:310)
==14093==  Address 0x61a1020 is 0 bytes after a block of size 704 free'd
==14093==    at 0x4C31D2F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1D6C71: ??? (in /usr/bin/python2.7)
==14093==    by 0x1D68B4: PyList_Append (in /usr/bin/python2.7)
==14093==    by 0x1F4BAD: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EE2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EE2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4A35: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==14093==    by 0x1F49E2: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==14093==    by 0x1F4930: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4548: ??? (in /usr/bin/python2.7)
==14093==  Block was alloc'd at
==14093==    at 0x4C31D2F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1D6C71: ??? (in /usr/bin/python2.7)
==14093==    by 0x1D68B4: PyList_Append (in /usr/bin/python2.7)
==14093==    by 0x1F4BAD: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EE2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EE2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4A35: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==14093==    by 0x1F49E2: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==14093==    by 0x1F4930: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4548: ??? (in /usr/bin/python2.7)
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x157BFF: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x212203: ??? (in /usr/bin/python2.7)
==14093==    by 0x211E1B: ??? (in /usr/bin/python2.7)
==14093==    by 0x23CFB4: _PyModule_Clear (in /usr/bin/python2.7)
==14093==    by 0x23C6E3: PyImport_Cleanup (in /usr/bin/python2.7)
==14093==    by 0x239927: Py_Finalize (in /usr/bin/python2.7)
==14093==    by 0x1D5073: Py_Main (in /usr/bin/python2.7)
==14093==    by 0x5064B96: (below main) (libc-start.c:310)
==14093==  Address 0x61aa020 is 0 bytes inside a block of size 96 free'd
==14093==    at 0x4C30D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1DCF74: ??? (in /usr/bin/python2.7)
==14093==    by 0x203501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x203231: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x203231: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x203231: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x203231: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x1FB628: PyEval_EvalCode (in /usr/bin/python2.7)
==14093==    by 0x1FB564: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==14093==    by 0x1F4592: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A56: ??? (in /usr/bin/python2.7)
==14093==  Block was alloc'd at
==14093==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1D5798: PyList_New (in /usr/bin/python2.7)
==14093==    by 0x21C22D: ??? (in /usr/bin/python2.7)
==14093==    by 0x1FE4C9: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x203231: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x203231: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x203231: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x203231: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x1FB628: PyEval_EvalCode (in /usr/bin/python2.7)
==14093==    by 0x1FB564: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==14093==    by 0x1F4592: ??? (in /usr/bin/python2.7)
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x157BFF: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x211FF5: ??? (in /usr/bin/python2.7)
==14093==    by 0x211E1B: ??? (in /usr/bin/python2.7)
==14093==    by 0x23CFB4: _PyModule_Clear (in /usr/bin/python2.7)
==14093==    by 0x23C6E3: PyImport_Cleanup (in /usr/bin/python2.7)
==14093==    by 0x239927: Py_Finalize (in /usr/bin/python2.7)
==14093==    by 0x1D5073: Py_Main (in /usr/bin/python2.7)
==14093==    by 0x5064B96: (below main) (libc-start.c:310)
==14093==  Address 0x61a3020 is 32 bytes before a block of size 576 in arena "client"
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x157BFF: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x211F3A: ??? (in /usr/bin/python2.7)
==14093==    by 0x23CFB4: _PyModule_Clear (in /usr/bin/python2.7)
==14093==    by 0x23C6E3: PyImport_Cleanup (in /usr/bin/python2.7)
==14093==    by 0x239927: Py_Finalize (in /usr/bin/python2.7)
==14093==    by 0x1D5073: Py_Main (in /usr/bin/python2.7)
==14093==    by 0x5064B96: (below main) (libc-start.c:310)
==14093==  Address 0x61a3020 is 32 bytes before a block of size 576 in arena "client"
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x157BFF: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x211F3A: ??? (in /usr/bin/python2.7)
==14093==    by 0x1D7700: PyDict_SetItem (in /usr/bin/python2.7)
==14093==    by 0x23CB56: _PyModule_Clear (in /usr/bin/python2.7)
==14093==    by 0x23C6E3: PyImport_Cleanup (in /usr/bin/python2.7)
==14093==    by 0x239927: Py_Finalize (in /usr/bin/python2.7)
==14093==    by 0x1D5073: Py_Main (in /usr/bin/python2.7)
==14093==    by 0x5064B96: (below main) (libc-start.c:310)
==14093==  Address 0x13d37020 is 288 bytes inside a block of size 645 free'd
==14093==    at 0x4C30D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x211FF5: ??? (in /usr/bin/python2.7)
==14093==    by 0x211E1B: ??? (in /usr/bin/python2.7)
==14093==    by 0x1D7700: PyDict_SetItem (in /usr/bin/python2.7)
==14093==    by 0x23CB56: _PyModule_Clear (in /usr/bin/python2.7)
==14093==    by 0x23C6E3: PyImport_Cleanup (in /usr/bin/python2.7)
==14093==    by 0x239927: Py_Finalize (in /usr/bin/python2.7)
==14093==    by 0x1D5073: Py_Main (in /usr/bin/python2.7)
==14093==    by 0x5064B96: (below main) (libc-start.c:310)
==14093==  Block was alloc'd at
==14093==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1E1AB1: PyString_FromStringAndSize (in /usr/bin/python2.7)
==14093==    by 0x1F4B40: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4ECC: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EE2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4A35: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==14093==    by 0x1F49E2: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==14093==    by 0x1F4930: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4548: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A56: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E5E10: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x157BFF: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x1EB45A: ??? (in /usr/bin/python2.7)
==14093==    by 0x23CFB4: _PyModule_Clear (in /usr/bin/python2.7)
==14093==    by 0x23C6E3: PyImport_Cleanup (in /usr/bin/python2.7)
==14093==    by 0x239927: Py_Finalize (in /usr/bin/python2.7)
==14093==    by 0x1D5073: Py_Main (in /usr/bin/python2.7)
==14093==    by 0x5064B96: (below main) (libc-start.c:310)
==14093==  Address 0x6222020 is 1,120 bytes inside a block of size 3,696 free'd
==14093==    at 0x4C31D2F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1D6C71: ??? (in /usr/bin/python2.7)
==14093==    by 0x1D68B4: PyList_Append (in /usr/bin/python2.7)
==14093==    by 0x1F4BAD: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EE2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4A35: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==14093==    by 0x1F49E2: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==14093==    by 0x1F4930: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4548: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A56: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E5E10: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==14093==  Block was alloc'd at
==14093==    at 0x4C31D2F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1D6C71: ??? (in /usr/bin/python2.7)
==14093==    by 0x1D68B4: PyList_Append (in /usr/bin/python2.7)
==14093==    by 0x1F4BAD: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EE2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4A35: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==14093==    by 0x1F49E2: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==14093==    by 0x1F4930: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4548: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A56: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E5E10: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x157BFF: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x1EB45A: ??? (in /usr/bin/python2.7)
==14093==    by 0x221D3D: ??? (in /usr/bin/python2.7)
==14093==    by 0x23CFB4: _PyModule_Clear (in /usr/bin/python2.7)
==14093==    by 0x23C6E3: PyImport_Cleanup (in /usr/bin/python2.7)
==14093==    by 0x239927: Py_Finalize (in /usr/bin/python2.7)
==14093==    by 0x1D5073: Py_Main (in /usr/bin/python2.7)
==14093==    by 0x5064B96: (below main) (libc-start.c:310)
==14093==  Address 0x63a2020 is 16 bytes before a block of size 1,008 free'd
==14093==    at 0x4C31D2F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1D6C71: ??? (in /usr/bin/python2.7)
==14093==    by 0x1D68B4: PyList_Append (in /usr/bin/python2.7)
==14093==    by 0x1F4BAD: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4F61: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EE2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EE2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4A35: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==14093==    by 0x1F49E2: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==14093==    by 0x1F4930: ??? (in /usr/bin/python2.7)
==14093==  Block was alloc'd at
==14093==    at 0x4C31D2F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1D6C71: ??? (in /usr/bin/python2.7)
==14093==    by 0x1D68B4: PyList_Append (in /usr/bin/python2.7)
==14093==    by 0x1F4BAD: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EF8: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D58: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EE2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EE2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4A35: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==14093==    by 0x1F49E2: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x157BFF: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x211F3A: ??? (in /usr/bin/python2.7)
==14093==    by 0x1EB45A: ??? (in /usr/bin/python2.7)
==14093==    by 0x221D3D: ??? (in /usr/bin/python2.7)
==14093==    by 0x23CFB4: _PyModule_Clear (in /usr/bin/python2.7)
==14093==    by 0x23C6E3: PyImport_Cleanup (in /usr/bin/python2.7)
==14093==    by 0x239927: Py_Finalize (in /usr/bin/python2.7)
==14093==    by 0x1D5073: Py_Main (in /usr/bin/python2.7)
==14093==    by 0x5064B96: (below main) (libc-start.c:310)
==14093==  Address 0x63a2020 is 16 bytes before a block of size 1,008 free'd
==14093==    at 0x4C31D2F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1D6C71: ??? (in /usr/bin/python2.7)
==14093==    by 0x1D68B4: PyList_Append (in /usr/bin/python2.7)
==14093==    by 0x1F4BAD: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4F61: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EE2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EE2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4A35: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==14093==    by 0x1F49E2: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==14093==    by 0x1F4930: ??? (in /usr/bin/python2.7)
==14093==  Block was alloc'd at
==14093==    at 0x4C31D2F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1D6C71: ??? (in /usr/bin/python2.7)
==14093==    by 0x1D68B4: PyList_Append (in /usr/bin/python2.7)
==14093==    by 0x1F4BAD: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EF8: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D58: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EE2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EE2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4A35: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==14093==    by 0x1F49E2: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x157BFF: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x23CFB4: _PyModule_Clear (in /usr/bin/python2.7)
==14093==    by 0x23C8AF: PyImport_Cleanup (in /usr/bin/python2.7)
==14093==    by 0x239927: Py_Finalize (in /usr/bin/python2.7)
==14093==    by 0x1D5073: Py_Main (in /usr/bin/python2.7)
==14093==    by 0x5064B96: (below main) (libc-start.c:310)
==14093==  Address 0x744a020 is 13,312 bytes inside a block of size 14,528 free'd
==14093==    at 0x4C30D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1F49ED: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==14093==    by 0x1F4930: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4548: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A56: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E5E10: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==14093==    by 0x1E79E7: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E777D: PyObject_Call (in /usr/bin/python2.7)
==14093==    by 0x2077FF: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==14093==    by 0x200C09: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x1FB628: PyEval_EvalCode (in /usr/bin/python2.7)
==14093==  Block was alloc'd at
==14093==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1F49B8: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==14093==    by 0x1F4930: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4548: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A56: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E5E10: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==14093==    by 0x1E79E7: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E777D: PyObject_Call (in /usr/bin/python2.7)
==14093==    by 0x2077FF: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==14093==    by 0x200C09: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x1FB628: PyEval_EvalCode (in /usr/bin/python2.7)
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x157BFF: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x211F3A: ??? (in /usr/bin/python2.7)
==14093==    by 0x23CFB4: _PyModule_Clear (in /usr/bin/python2.7)
==14093==    by 0x23C8AF: PyImport_Cleanup (in /usr/bin/python2.7)
==14093==    by 0x239927: Py_Finalize (in /usr/bin/python2.7)
==14093==    by 0x1D5073: Py_Main (in /usr/bin/python2.7)
==14093==    by 0x5064B96: (below main) (libc-start.c:310)
==14093==  Address 0x7531020 is 6,224 bytes inside a block of size 6,569 free'd
==14093==    at 0x4C30D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1F49ED: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==14093==    by 0x1F4930: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4548: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A56: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E5E10: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==14093==    by 0x1E79E7: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E777D: PyObject_Call (in /usr/bin/python2.7)
==14093==    by 0x2077FF: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==14093==    by 0x200C09: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x1FB628: PyEval_EvalCode (in /usr/bin/python2.7)
==14093==  Block was alloc'd at
==14093==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1F49B8: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==14093==    by 0x1F4930: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4548: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A56: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E5E10: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==14093==    by 0x1E79E7: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E777D: PyObject_Call (in /usr/bin/python2.7)
==14093==    by 0x2077FF: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==14093==    by 0x200C09: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x1FB628: PyEval_EvalCode (in /usr/bin/python2.7)
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x157BFF: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x212203: ??? (in /usr/bin/python2.7)
==14093==    by 0x211E1B: ??? (in /usr/bin/python2.7)
==14093==    by 0x1D7700: PyDict_SetItem (in /usr/bin/python2.7)
==14093==    by 0x23CB56: _PyModule_Clear (in /usr/bin/python2.7)
==14093==    by 0x23C8AF: PyImport_Cleanup (in /usr/bin/python2.7)
==14093==    by 0x239927: Py_Finalize (in /usr/bin/python2.7)
==14093==    by 0x1D5073: Py_Main (in /usr/bin/python2.7)
==14093==    by 0x5064B96: (below main) (libc-start.c:310)
==14093==  Address 0x73bb020 is 1,984 bytes inside a block of size 3,072 free'd
==14093==    at 0x4C30D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1DA9C7: ??? (in /usr/bin/python2.7)
==14093==    by 0x1FF2D2: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x203C37: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x1FB628: PyEval_EvalCode (in /usr/bin/python2.7)
==14093==    by 0x1FB564: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==14093==    by 0x1F4592: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A56: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E5E10: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==14093==    by 0x1E79E7: ??? (in /usr/bin/python2.7)
==14093==  Block was alloc'd at
==14093==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1DA7D1: ??? (in /usr/bin/python2.7)
==14093==    by 0x1FF2D2: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x203C37: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x1FB628: PyEval_EvalCode (in /usr/bin/python2.7)
==14093==    by 0x1FB564: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==14093==    by 0x1F4592: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A56: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E5E10: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==14093==    by 0x1E79E7: ??? (in /usr/bin/python2.7)
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x157BFF: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x1EB285: ??? (in /usr/bin/python2.7)
==14093==    by 0x212017: ??? (in /usr/bin/python2.7)
==14093==    by 0x211E1B: ??? (in /usr/bin/python2.7)
==14093==    by 0x1D7700: PyDict_SetItem (in /usr/bin/python2.7)
==14093==    by 0x23CB56: _PyModule_Clear (in /usr/bin/python2.7)
==14093==    by 0x23C8AF: PyImport_Cleanup (in /usr/bin/python2.7)
==14093==    by 0x239927: Py_Finalize (in /usr/bin/python2.7)
==14093==    by 0x1D5073: Py_Main (in /usr/bin/python2.7)
==14093==    by 0x5064B96: (below main) (libc-start.c:310)
==14093==  Address 0x738a020 is 16 bytes after a block of size 1,008 free'd
==14093==    at 0x4C31D2F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1D6C71: ??? (in /usr/bin/python2.7)
==14093==    by 0x1D68B4: PyList_Append (in /usr/bin/python2.7)
==14093==    by 0x1F4BAD: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EE2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EE2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4A35: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==14093==    by 0x1F49E2: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==14093==    by 0x1F4930: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4548: ??? (in /usr/bin/python2.7)
==14093==  Block was alloc'd at
==14093==    at 0x4C31D2F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1D6C71: ??? (in /usr/bin/python2.7)
==14093==    by 0x1D68B4: PyList_Append (in /usr/bin/python2.7)
==14093==    by 0x1F4BAD: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4CF4: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4F0C: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EE2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4A35: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==14093==    by 0x1F49E2: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==14093==    by 0x1F4930: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4548: ??? (in /usr/bin/python2.7)
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x157BFF: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x211FF5: ??? (in /usr/bin/python2.7)
==14093==    by 0x211E1B: ??? (in /usr/bin/python2.7)
==14093==    by 0x1EB45A: ??? (in /usr/bin/python2.7)
==14093==    by 0x221D3D: ??? (in /usr/bin/python2.7)
==14093==    by 0x23CFB4: _PyModule_Clear (in /usr/bin/python2.7)
==14093==    by 0x23C8AF: PyImport_Cleanup (in /usr/bin/python2.7)
==14093==    by 0x239927: Py_Finalize (in /usr/bin/python2.7)
==14093==    by 0x1D5073: Py_Main (in /usr/bin/python2.7)
==14093==    by 0x5064B96: (below main) (libc-start.c:310)
==14093==  Address 0x12679020 is 32 bytes inside a block of size 280 free'd
==14093==    at 0x4C31D2F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1D6C71: ??? (in /usr/bin/python2.7)
==14093==    by 0x1D68B4: PyList_Append (in /usr/bin/python2.7)
==14093==    by 0x1F4BAD: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D18: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EF8: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D38: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EE2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EE2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4A35: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==14093==    by 0x1F49E2: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==14093==  Block was alloc'd at
==14093==    at 0x4C31D2F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1D6C71: ??? (in /usr/bin/python2.7)
==14093==    by 0x1D68B4: PyList_Append (in /usr/bin/python2.7)
==14093==    by 0x1F4BAD: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4CD0: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EF8: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D18: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EE2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EE2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4A35: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==14093==    by 0x1F49E2: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x157BFF: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x1D7700: PyDict_SetItem (in /usr/bin/python2.7)
==14093==    by 0x23CB56: _PyModule_Clear (in /usr/bin/python2.7)
==14093==    by 0x23C8AF: PyImport_Cleanup (in /usr/bin/python2.7)
==14093==    by 0x239927: Py_Finalize (in /usr/bin/python2.7)
==14093==    by 0x1D5073: Py_Main (in /usr/bin/python2.7)
==14093==    by 0x5064B96: (below main) (libc-start.c:310)
==14093==  Address 0x7421020 is 256 bytes inside a block of size 368 free'd
==14093==    at 0x4C31D2F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1D6C71: ??? (in /usr/bin/python2.7)
==14093==    by 0x1D68B4: PyList_Append (in /usr/bin/python2.7)
==14093==    by 0x1F4BAD: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4CD0: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EF8: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EE2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EE2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4A35: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==14093==    by 0x1F49E2: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==14093==  Block was alloc'd at
==14093==    at 0x4C31D2F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1D6C71: ??? (in /usr/bin/python2.7)
==14093==    by 0x1D68B4: PyList_Append (in /usr/bin/python2.7)
==14093==    by 0x1F4BAD: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4F0C: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D38: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EE2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EE2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4A35: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==14093==    by 0x1F49E2: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x157BFF: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x1EB16B: ??? (in /usr/bin/python2.7)
==14093==    by 0x1EB45A: ??? (in /usr/bin/python2.7)
==14093==    by 0x1D7700: PyDict_SetItem (in /usr/bin/python2.7)
==14093==    by 0x23CB56: _PyModule_Clear (in /usr/bin/python2.7)
==14093==    by 0x23C8AF: PyImport_Cleanup (in /usr/bin/python2.7)
==14093==    by 0x239927: Py_Finalize (in /usr/bin/python2.7)
==14093==    by 0x1D5073: Py_Main (in /usr/bin/python2.7)
==14093==    by 0x5064B96: (below main) (libc-start.c:310)
==14093==  Address 0x13da5020 is 0 bytes after a block of size 1,184 free'd
==14093==    at 0x4C31D2F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1DC072: ??? (in /usr/bin/python2.7)
==14093==    by 0x203595: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x2035FD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x203231: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x203231: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x203231: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x203231: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x2035FD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==  Block was alloc'd at
==14093==    at 0x4C31D2F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x21FCB2: ??? (in /usr/bin/python2.7)
==14093==    by 0x203595: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x2035FD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x203231: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x203231: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x203231: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x203231: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x203231: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x203231: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x203231: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x157BFF: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x247DD8: ??? (in /usr/bin/python2.7)
==14093==    by 0x1EB16B: ??? (in /usr/bin/python2.7)
==14093==    by 0x1EB45A: ??? (in /usr/bin/python2.7)
==14093==    by 0x1D7700: PyDict_SetItem (in /usr/bin/python2.7)
==14093==    by 0x23CB56: _PyModule_Clear (in /usr/bin/python2.7)
==14093==    by 0x23C8AF: PyImport_Cleanup (in /usr/bin/python2.7)
==14093==    by 0x239927: Py_Finalize (in /usr/bin/python2.7)
==14093==    by 0x1D5073: Py_Main (in /usr/bin/python2.7)
==14093==    by 0x5064B96: (below main) (libc-start.c:310)
==14093==  Address 0x13d36020 is 1,936 bytes inside a block of size 4,208 free'd
==14093==    at 0x4C31D2F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1D6C71: ??? (in /usr/bin/python2.7)
==14093==    by 0x1D68B4: PyList_Append (in /usr/bin/python2.7)
==14093==    by 0x1F4BAD: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4F0C: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EE2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4A35: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==14093==    by 0x1F49E2: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==14093==    by 0x1F4930: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4548: ??? (in /usr/bin/python2.7)
==14093==  Block was alloc'd at
==14093==    at 0x4C31D2F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1D6C71: ??? (in /usr/bin/python2.7)
==14093==    by 0x1D68B4: PyList_Append (in /usr/bin/python2.7)
==14093==    by 0x1F4BAD: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EE2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4A35: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==14093==    by 0x1F49E2: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==14093==    by 0x1F4930: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4548: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A56: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E5E10: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x157BFF: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x211F3A: ??? (in /usr/bin/python2.7)
==14093==    by 0x1EB45A: ??? (in /usr/bin/python2.7)
==14093==    by 0x1D7700: PyDict_SetItem (in /usr/bin/python2.7)
==14093==    by 0x23CB56: _PyModule_Clear (in /usr/bin/python2.7)
==14093==    by 0x23C8AF: PyImport_Cleanup (in /usr/bin/python2.7)
==14093==    by 0x239927: Py_Finalize (in /usr/bin/python2.7)
==14093==    by 0x1D5073: Py_Main (in /usr/bin/python2.7)
==14093==    by 0x5064B96: (below main) (libc-start.c:310)
==14093==  Address 0x12f28020 is 31,632 bytes inside a block of size 31,661 free'd
==14093==    at 0x4C30D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1F49ED: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==14093==    by 0x1F4930: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4548: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A56: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6465: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==14093==    by 0x1E79E7: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E777D: PyObject_Call (in /usr/bin/python2.7)
==14093==    by 0x2077FF: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==14093==    by 0x200C09: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x1FB628: PyEval_EvalCode (in /usr/bin/python2.7)
==14093==  Block was alloc'd at
==14093==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1F49B8: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==14093==    by 0x1F4930: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4548: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A56: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6465: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==14093==    by 0x1E79E7: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E777D: PyObject_Call (in /usr/bin/python2.7)
==14093==    by 0x2077FF: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==14093==    by 0x200C09: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x1FB628: PyEval_EvalCode (in /usr/bin/python2.7)
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x157BFF: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x238094: ??? (in /usr/bin/python2.7)
==14093==    by 0x23CFB4: _PyModule_Clear (in /usr/bin/python2.7)
==14093==    by 0x23C8AF: PyImport_Cleanup (in /usr/bin/python2.7)
==14093==    by 0x239927: Py_Finalize (in /usr/bin/python2.7)
==14093==    by 0x1D5073: Py_Main (in /usr/bin/python2.7)
==14093==    by 0x5064B96: (below main) (libc-start.c:310)
==14093==  Address 0x14a84020 is 448 bytes inside a block of size 1,399 free'd
==14093==    at 0x4C30D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x238094: ??? (in /usr/bin/python2.7)
==14093==    by 0x23CFB4: _PyModule_Clear (in /usr/bin/python2.7)
==14093==    by 0x23C8AF: PyImport_Cleanup (in /usr/bin/python2.7)
==14093==    by 0x239927: Py_Finalize (in /usr/bin/python2.7)
==14093==    by 0x1D5073: Py_Main (in /usr/bin/python2.7)
==14093==    by 0x5064B96: (below main) (libc-start.c:310)
==14093==  Block was alloc'd at
==14093==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1E1AB1: PyString_FromStringAndSize (in /usr/bin/python2.7)
==14093==    by 0x21DD36: ??? (in /usr/bin/python2.7)
==14093==    by 0x203595: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x203C37: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x217618: ??? (in /usr/bin/python2.7)
==14093==    by 0x2300DD: ??? (in /usr/bin/python2.7)
==14093==    by 0x22FCE9: ??? (in /usr/bin/python2.7)
==14093==    by 0x1EC86A: ??? (in /usr/bin/python2.7)
==14093==    by 0x20341F: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x157BFF: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x211F3A: ??? (in /usr/bin/python2.7)
==14093==    by 0x235E85: ??? (in /usr/bin/python2.7)
==14093==    by 0x1EB16B: ??? (in /usr/bin/python2.7)
==14093==    by 0x211F66: ??? (in /usr/bin/python2.7)
==14093==    by 0x23CFB4: _PyModule_Clear (in /usr/bin/python2.7)
==14093==    by 0x23C8AF: PyImport_Cleanup (in /usr/bin/python2.7)
==14093==    by 0x239927: Py_Finalize (in /usr/bin/python2.7)
==14093==    by 0x1D5073: Py_Main (in /usr/bin/python2.7)
==14093==    by 0x5064B96: (below main) (libc-start.c:310)
==14093==  Address 0x1273d020 is 208 bytes inside a block of size 607 free'd
==14093==    at 0x4C30D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x211F3A: ??? (in /usr/bin/python2.7)
==14093==    by 0x23CFB4: _PyModule_Clear (in /usr/bin/python2.7)
==14093==    by 0x23C8AF: PyImport_Cleanup (in /usr/bin/python2.7)
==14093==    by 0x239927: Py_Finalize (in /usr/bin/python2.7)
==14093==    by 0x1D5073: Py_Main (in /usr/bin/python2.7)
==14093==    by 0x5064B96: (below main) (libc-start.c:310)
==14093==  Block was alloc'd at
==14093==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1E1AB1: PyString_FromStringAndSize (in /usr/bin/python2.7)
==14093==    by 0x1F4B40: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4CD0: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EE2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EE2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4A35: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==14093==    by 0x1F49E2: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==14093==    by 0x1F4930: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4548: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A56: ??? (in /usr/bin/python2.7)
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x157BFF: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x238094: ??? (in /usr/bin/python2.7)
==14093==    by 0x238094: ??? (in /usr/bin/python2.7)
==14093==    by 0x23CFB4: _PyModule_Clear (in /usr/bin/python2.7)
==14093==    by 0x23C8AF: PyImport_Cleanup (in /usr/bin/python2.7)
==14093==    by 0x239927: Py_Finalize (in /usr/bin/python2.7)
==14093==    by 0x1D5073: Py_Main (in /usr/bin/python2.7)
==14093==    by 0x5064B96: (below main) (libc-start.c:310)
==14093==  Address 0x149f9020 is 240 bytes inside a block of size 1,245 free'd
==14093==    at 0x4C31D2F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1EA774: PyString_FromFormatV (in /usr/bin/python2.7)
==14093==    by 0x24DC28: PyString_FromFormat (in /usr/bin/python2.7)
==14093==    by 0xFC94840: ??? (in /usr/local/lib/python2.7/dist-packages/numpy/core/umath.so)
==14093==    by 0x2133A8: ??? (in /usr/bin/python2.7)
==14093==    by 0x15B161: _PyObject_GenericGetAttrWithDict (in /usr/bin/python2.7)
==14093==    by 0x1FE5CF: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x203C37: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x217618: ??? (in /usr/bin/python2.7)
==14093==    by 0x2300DD: ??? (in /usr/bin/python2.7)
==14093==  Block was alloc'd at
==14093==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1E1AB1: PyString_FromStringAndSize (in /usr/bin/python2.7)
==14093==    by 0x1EA499: PyString_FromFormatV (in /usr/bin/python2.7)
==14093==    by 0x24DC28: PyString_FromFormat (in /usr/bin/python2.7)
==14093==    by 0xFC94840: ??? (in /usr/local/lib/python2.7/dist-packages/numpy/core/umath.so)
==14093==    by 0x2133A8: ??? (in /usr/bin/python2.7)
==14093==    by 0x15B161: _PyObject_GenericGetAttrWithDict (in /usr/bin/python2.7)
==14093==    by 0x1FE5CF: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x203C37: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x217618: ??? (in /usr/bin/python2.7)
==14093== 
==14093== Conditional jump or move depends on uninitialised value(s)
==14093==    at 0x157C08: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x238094: ??? (in /usr/bin/python2.7)
==14093==    by 0x23CFB4: _PyModule_Clear (in /usr/bin/python2.7)
==14093==    by 0x23C8AF: PyImport_Cleanup (in /usr/bin/python2.7)
==14093==    by 0x239927: Py_Finalize (in /usr/bin/python2.7)
==14093==    by 0x1D5073: Py_Main (in /usr/bin/python2.7)
==14093==    by 0x5064B96: (below main) (libc-start.c:310)
==14093== 
==14093== Use of uninitialised value of size 8
==14093==    at 0x157C1C: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x238094: ??? (in /usr/bin/python2.7)
==14093==    by 0x23CFB4: _PyModule_Clear (in /usr/bin/python2.7)
==14093==    by 0x23C8AF: PyImport_Cleanup (in /usr/bin/python2.7)
==14093==    by 0x239927: Py_Finalize (in /usr/bin/python2.7)
==14093==    by 0x1D5073: Py_Main (in /usr/bin/python2.7)
==14093==    by 0x5064B96: (below main) (libc-start.c:310)
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x157BFF: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x238094: ??? (in /usr/bin/python2.7)
==14093==    by 0x21AC89: ??? (in /usr/bin/python2.7)
==14093==    by 0x23CFB4: _PyModule_Clear (in /usr/bin/python2.7)
==14093==    by 0x23C8AF: PyImport_Cleanup (in /usr/bin/python2.7)
==14093==    by 0x239927: Py_Finalize (in /usr/bin/python2.7)
==14093==    by 0x1D5073: Py_Main (in /usr/bin/python2.7)
==14093==    by 0x5064B96: (below main) (libc-start.c:310)
==14093==  Address 0x149fd020 is 1,056 bytes inside a block of size 1,314 free'd
==14093==    at 0x4C31D2F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1EA774: PyString_FromFormatV (in /usr/bin/python2.7)
==14093==    by 0x24DC28: PyString_FromFormat (in /usr/bin/python2.7)
==14093==    by 0xFC94840: ??? (in /usr/local/lib/python2.7/dist-packages/numpy/core/umath.so)
==14093==    by 0x2133A8: ??? (in /usr/bin/python2.7)
==14093==    by 0x15B161: _PyObject_GenericGetAttrWithDict (in /usr/bin/python2.7)
==14093==    by 0x1FE5CF: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x203C37: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x217618: ??? (in /usr/bin/python2.7)
==14093==    by 0x2300DD: ??? (in /usr/bin/python2.7)
==14093==  Block was alloc'd at
==14093==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1E1AB1: PyString_FromStringAndSize (in /usr/bin/python2.7)
==14093==    by 0x1EA499: PyString_FromFormatV (in /usr/bin/python2.7)
==14093==    by 0x24DC28: PyString_FromFormat (in /usr/bin/python2.7)
==14093==    by 0xFC94840: ??? (in /usr/local/lib/python2.7/dist-packages/numpy/core/umath.so)
==14093==    by 0x2133A8: ??? (in /usr/bin/python2.7)
==14093==    by 0x15B161: _PyObject_GenericGetAttrWithDict (in /usr/bin/python2.7)
==14093==    by 0x1FE5CF: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x203C37: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x217618: ??? (in /usr/bin/python2.7)
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x157BFF: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x1EB285: ??? (in /usr/bin/python2.7)
==14093==    by 0x21205C: ??? (in /usr/bin/python2.7)
==14093==    by 0x211E1B: ??? (in /usr/bin/python2.7)
==14093==    by 0x23CFB4: _PyModule_Clear (in /usr/bin/python2.7)
==14093==    by 0x23C8AF: PyImport_Cleanup (in /usr/bin/python2.7)
==14093==    by 0x239927: Py_Finalize (in /usr/bin/python2.7)
==14093==    by 0x1D5073: Py_Main (in /usr/bin/python2.7)
==14093==    by 0x5064B96: (below main) (libc-start.c:310)
==14093==  Address 0x13c67020 is 2,000 bytes inside a block of size 3,240 free'd
==14093==    at 0x4C31D2F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1D6C71: ??? (in /usr/bin/python2.7)
==14093==    by 0x1D68B4: PyList_Append (in /usr/bin/python2.7)
==14093==    by 0x1F4BAD: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4F0C: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EE2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4A35: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==14093==    by 0x1F49E2: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==14093==    by 0x1F4930: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4548: ??? (in /usr/bin/python2.7)
==14093==  Block was alloc'd at
==14093==    at 0x4C31D2F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1D6C71: ??? (in /usr/bin/python2.7)
==14093==    by 0x1D68B4: PyList_Append (in /usr/bin/python2.7)
==14093==    by 0x1F4BAD: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EF8: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EE2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4A35: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==14093==    by 0x1F49E2: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==14093==    by 0x1F4930: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4548: ??? (in /usr/bin/python2.7)
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x157BFF: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x2121CB: ??? (in /usr/bin/python2.7)
==14093==    by 0x211E1B: ??? (in /usr/bin/python2.7)
==14093==    by 0x23CFB4: _PyModule_Clear (in /usr/bin/python2.7)
==14093==    by 0x23C8AF: PyImport_Cleanup (in /usr/bin/python2.7)
==14093==    by 0x239927: Py_Finalize (in /usr/bin/python2.7)
==14093==    by 0x1D5073: Py_Main (in /usr/bin/python2.7)
==14093==    by 0x5064B96: (below main) (libc-start.c:310)
==14093==  Address 0x13c68020 is 1,856 bytes inside a block of size 3,696 free'd
==14093==    at 0x4C30D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1DCF74: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4A4F: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==14093==    by 0x1F49E2: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==14093==    by 0x1F4930: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4548: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A56: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E5E10: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==14093==    by 0x1E79E7: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E777D: PyObject_Call (in /usr/bin/python2.7)
==14093==    by 0x2077FF: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==14093==    by 0x200C09: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==  Block was alloc'd at
==14093==    at 0x4C31D2F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1D6C71: ??? (in /usr/bin/python2.7)
==14093==    by 0x1D68B4: PyList_Append (in /usr/bin/python2.7)
==14093==    by 0x1F4BAD: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4F0C: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EE2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4A35: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==14093==    by 0x1F49E2: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==14093==    by 0x1F4930: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4548: ??? (in /usr/bin/python2.7)
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x157BFF: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x2120E6: ??? (in /usr/bin/python2.7)
==14093==    by 0x211E1B: ??? (in /usr/bin/python2.7)
==14093==    by 0x1D7700: PyDict_SetItem (in /usr/bin/python2.7)
==14093==    by 0x23CB56: _PyModule_Clear (in /usr/bin/python2.7)
==14093==    by 0x23C8AF: PyImport_Cleanup (in /usr/bin/python2.7)
==14093==    by 0x239927: Py_Finalize (in /usr/bin/python2.7)
==14093==    by 0x1D5073: Py_Main (in /usr/bin/python2.7)
==14093==    by 0x5064B96: (below main) (libc-start.c:310)
==14093==  Address 0x61da020 is 1,200 bytes inside a block of size 1,608 free'd
==14093==    at 0x4C31D2F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1D6C71: ??? (in /usr/bin/python2.7)
==14093==    by 0x1D68B4: PyList_Append (in /usr/bin/python2.7)
==14093==    by 0x1F4BAD: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4F0C: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EE2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4A35: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==14093==    by 0x1F49E2: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==14093==    by 0x1F4930: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4548: ??? (in /usr/bin/python2.7)
==14093==  Block was alloc'd at
==14093==    at 0x4C31D2F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1D6C71: ??? (in /usr/bin/python2.7)
==14093==    by 0x1D68B4: PyList_Append (in /usr/bin/python2.7)
==14093==    by 0x1F4BAD: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EF8: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EE2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4A35: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==14093==    by 0x1F49E2: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==14093==    by 0x1F4930: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4548: ??? (in /usr/bin/python2.7)
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x157BFF: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x212203: ??? (in /usr/bin/python2.7)
==14093==    by 0x211E1B: ??? (in /usr/bin/python2.7)
==14093==    by 0x1EB45A: ??? (in /usr/bin/python2.7)
==14093==    by 0x221D3D: ??? (in /usr/bin/python2.7)
==14093==    by 0x23CFB4: _PyModule_Clear (in /usr/bin/python2.7)
==14093==    by 0x23C8AF: PyImport_Cleanup (in /usr/bin/python2.7)
==14093==    by 0x239927: Py_Finalize (in /usr/bin/python2.7)
==14093==    by 0x1D5073: Py_Main (in /usr/bin/python2.7)
==14093==    by 0x5064B96: (below main) (libc-start.c:310)
==14093==  Address 0x1499c020 is 512 bytes inside a block of size 768 free'd
==14093==    at 0x4C30D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1EB527: ??? (in /usr/bin/python2.7)
==14093==    by 0x22147B: ??? (in /usr/bin/python2.7)
==14093==    by 0x1EB45A: ??? (in /usr/bin/python2.7)
==14093==    by 0x22147B: ??? (in /usr/bin/python2.7)
==14093==    by 0x1EB16B: ??? (in /usr/bin/python2.7)
==14093==    by 0x1EB16B: ??? (in /usr/bin/python2.7)
==14093==    by 0x1DCF67: ??? (in /usr/bin/python2.7)
==14093==    by 0x1EB45A: ??? (in /usr/bin/python2.7)
==14093==    by 0x22147B: ??? (in /usr/bin/python2.7)
==14093==    by 0x1DCF67: ??? (in /usr/bin/python2.7)
==14093==    by 0x1EB16B: ??? (in /usr/bin/python2.7)
==14093==  Block was alloc'd at
==14093==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1DA7D1: ??? (in /usr/bin/python2.7)
==14093==    by 0x16A90A: ??? (in /usr/bin/python2.7)
==14093==    by 0x1FEEA3: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x2035FD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x2035FD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x203C37: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x2035FD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093== 
==14093== Conditional jump or move depends on uninitialised value(s)
==14093==    at 0x157C08: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x212203: ??? (in /usr/bin/python2.7)
==14093==    by 0x211E1B: ??? (in /usr/bin/python2.7)
==14093==    by 0x1D7700: PyDict_SetItem (in /usr/bin/python2.7)
==14093==    by 0x23CB56: _PyModule_Clear (in /usr/bin/python2.7)
==14093==    by 0x23C8AF: PyImport_Cleanup (in /usr/bin/python2.7)
==14093==    by 0x239927: Py_Finalize (in /usr/bin/python2.7)
==14093==    by 0x1D5073: Py_Main (in /usr/bin/python2.7)
==14093==    by 0x5064B96: (below main) (libc-start.c:310)
==14093== 
==14093== Use of uninitialised value of size 8
==14093==    at 0x157C1C: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x212203: ??? (in /usr/bin/python2.7)
==14093==    by 0x211E1B: ??? (in /usr/bin/python2.7)
==14093==    by 0x1D7700: PyDict_SetItem (in /usr/bin/python2.7)
==14093==    by 0x23CB56: _PyModule_Clear (in /usr/bin/python2.7)
==14093==    by 0x23C8AF: PyImport_Cleanup (in /usr/bin/python2.7)
==14093==    by 0x239927: Py_Finalize (in /usr/bin/python2.7)
==14093==    by 0x1D5073: Py_Main (in /usr/bin/python2.7)
==14093==    by 0x5064B96: (below main) (libc-start.c:310)
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x157BFF: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x211FF5: ??? (in /usr/bin/python2.7)
==14093==    by 0x211E1B: ??? (in /usr/bin/python2.7)
==14093==    by 0x1EB16B: ??? (in /usr/bin/python2.7)
==14093==    by 0x1EB45A: ??? (in /usr/bin/python2.7)
==14093==    by 0x1D7700: PyDict_SetItem (in /usr/bin/python2.7)
==14093==    by 0x23CB56: _PyModule_Clear (in /usr/bin/python2.7)
==14093==    by 0x23C8AF: PyImport_Cleanup (in /usr/bin/python2.7)
==14093==    by 0x239927: Py_Finalize (in /usr/bin/python2.7)
==14093==    by 0x1D5073: Py_Main (in /usr/bin/python2.7)
==14093==    by 0x5064B96: (below main) (libc-start.c:310)
==14093==  Address 0x1275c020 is 256 bytes inside a block of size 1,384 free'd
==14093==    at 0x4C31D2F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1D6C71: ??? (in /usr/bin/python2.7)
==14093==    by 0x1D68B4: PyList_Append (in /usr/bin/python2.7)
==14093==    by 0x1F4BAD: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EF8: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EE2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4A35: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==14093==    by 0x1F49E2: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==14093==    by 0x1F4930: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4548: ??? (in /usr/bin/python2.7)
==14093==  Block was alloc'd at
==14093==    at 0x4C31D2F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1D6C71: ??? (in /usr/bin/python2.7)
==14093==    by 0x1D68B4: PyList_Append (in /usr/bin/python2.7)
==14093==    by 0x1F4BAD: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4F0C: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EE2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4A35: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==14093==    by 0x1F49E2: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==14093==    by 0x1F4930: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4548: ??? (in /usr/bin/python2.7)
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x157BFF: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x211F3A: ??? (in /usr/bin/python2.7)
==14093==    by 0x1EB16B: ??? (in /usr/bin/python2.7)
==14093==    by 0x1EB45A: ??? (in /usr/bin/python2.7)
==14093==    by 0x1D7700: PyDict_SetItem (in /usr/bin/python2.7)
==14093==    by 0x23CB56: _PyModule_Clear (in /usr/bin/python2.7)
==14093==    by 0x23C8AF: PyImport_Cleanup (in /usr/bin/python2.7)
==14093==    by 0x239927: Py_Finalize (in /usr/bin/python2.7)
==14093==    by 0x1D5073: Py_Main (in /usr/bin/python2.7)
==14093==    by 0x5064B96: (below main) (libc-start.c:310)
==14093==  Address 0x1275b020 is 768 bytes inside a block of size 848 free'd
==14093==    at 0x4C31D2F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1D6C71: ??? (in /usr/bin/python2.7)
==14093==    by 0x1D68B4: PyList_Append (in /usr/bin/python2.7)
==14093==    by 0x1F4BAD: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4F61: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EE2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4A35: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==14093==    by 0x1F49E2: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==14093==    by 0x1F4930: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4548: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A56: ??? (in /usr/bin/python2.7)
==14093==  Block was alloc'd at
==14093==    at 0x4C31D2F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1D6C71: ??? (in /usr/bin/python2.7)
==14093==    by 0x1D68B4: PyList_Append (in /usr/bin/python2.7)
==14093==    by 0x1F4BAD: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4F0C: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EE2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4A35: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==14093==    by 0x1F49E2: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==14093==    by 0x1F4930: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4548: ??? (in /usr/bin/python2.7)
==14093== 
==14093== Conditional jump or move depends on uninitialised value(s)
==14093==    at 0x157C08: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x211FF5: ??? (in /usr/bin/python2.7)
==14093==    by 0x211E1B: ??? (in /usr/bin/python2.7)
==14093==    by 0x1D7700: PyDict_SetItem (in /usr/bin/python2.7)
==14093==    by 0x23CB56: _PyModule_Clear (in /usr/bin/python2.7)
==14093==    by 0x23C8AF: PyImport_Cleanup (in /usr/bin/python2.7)
==14093==    by 0x239927: Py_Finalize (in /usr/bin/python2.7)
==14093==    by 0x1D5073: Py_Main (in /usr/bin/python2.7)
==14093==    by 0x5064B96: (below main) (libc-start.c:310)
==14093== 
==14093== Use of uninitialised value of size 8
==14093==    at 0x157C1C: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x211FF5: ??? (in /usr/bin/python2.7)
==14093==    by 0x211E1B: ??? (in /usr/bin/python2.7)
==14093==    by 0x1D7700: PyDict_SetItem (in /usr/bin/python2.7)
==14093==    by 0x23CB56: _PyModule_Clear (in /usr/bin/python2.7)
==14093==    by 0x23C8AF: PyImport_Cleanup (in /usr/bin/python2.7)
==14093==    by 0x239927: Py_Finalize (in /usr/bin/python2.7)
==14093==    by 0x1D5073: Py_Main (in /usr/bin/python2.7)
==14093==    by 0x5064B96: (below main) (libc-start.c:310)
==14093== 
==14093== Conditional jump or move depends on uninitialised value(s)
==14093==    at 0x157C08: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x211F3A: ??? (in /usr/bin/python2.7)
==14093==    by 0x23CFB4: _PyModule_Clear (in /usr/bin/python2.7)
==14093==    by 0x23C8AF: PyImport_Cleanup (in /usr/bin/python2.7)
==14093==    by 0x239927: Py_Finalize (in /usr/bin/python2.7)
==14093==    by 0x1D5073: Py_Main (in /usr/bin/python2.7)
==14093==    by 0x5064B96: (below main) (libc-start.c:310)
==14093== 
==14093== Use of uninitialised value of size 8
==14093==    at 0x157C1C: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x211F3A: ??? (in /usr/bin/python2.7)
==14093==    by 0x23CFB4: _PyModule_Clear (in /usr/bin/python2.7)
==14093==    by 0x23C8AF: PyImport_Cleanup (in /usr/bin/python2.7)
==14093==    by 0x239927: Py_Finalize (in /usr/bin/python2.7)
==14093==    by 0x1D5073: Py_Main (in /usr/bin/python2.7)
==14093==    by 0x5064B96: (below main) (libc-start.c:310)
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x157BFF: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x1EB45A: ??? (in /usr/bin/python2.7)
==14093==    by 0x1EB45A: ??? (in /usr/bin/python2.7)
==14093==    by 0x23D74C: _PyImport_Fini (in /usr/bin/python2.7)
==14093==    by 0x23992C: Py_Finalize (in /usr/bin/python2.7)
==14093==    by 0x1D5073: Py_Main (in /usr/bin/python2.7)
==14093==    by 0x5064B96: (below main) (libc-start.c:310)
==14093==  Address 0x749d020 is 3,216 bytes inside a block of size 4,097 free'd
==14093==    at 0x4C30D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1EC096: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A32: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E5E10: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==14093==    by 0x1E79E7: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E74AD: PyObject_CallFunction (in /usr/bin/python2.7)
==14093==    by 0x1E5962: PyImport_Import (in /usr/bin/python2.7)
==14093==    by 0x1E587C: PyImport_ImportModule (in /usr/bin/python2.7)
==14093==    by 0x1823E1: ??? (in /usr/bin/python2.7)
==14093==    by 0x29D8E7: initcPickle (in /usr/bin/python2.7)
==14093==    by 0x1EC4A2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1EC399: ??? (in /usr/bin/python2.7)
==14093==  Block was alloc'd at
==14093==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1EBB08: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A32: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E5E10: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==14093==    by 0x1E79E7: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E74AD: PyObject_CallFunction (in /usr/bin/python2.7)
==14093==    by 0x1E5962: PyImport_Import (in /usr/bin/python2.7)
==14093==    by 0x1E587C: PyImport_ImportModule (in /usr/bin/python2.7)
==14093==    by 0x1823E1: ??? (in /usr/bin/python2.7)
==14093==    by 0x29D8E7: initcPickle (in /usr/bin/python2.7)
==14093==    by 0x1EC4A2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1EC399: ??? (in /usr/bin/python2.7)
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x157BFF: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x211FF5: ??? (in /usr/bin/python2.7)
==14093==    by 0x211E1B: ??? (in /usr/bin/python2.7)
==14093==    by 0x1DCF67: ??? (in /usr/bin/python2.7)
==14093==    by 0x23F860: PyInterpreterState_Clear (in /usr/bin/python2.7)
==14093==    by 0x239934: Py_Finalize (in /usr/bin/python2.7)
==14093==    by 0x1D5073: Py_Main (in /usr/bin/python2.7)
==14093==    by 0x5064B96: (below main) (libc-start.c:310)
==14093==  Address 0x638c020 is 3,856 bytes inside a block of size 4,370 free'd
==14093==    at 0x4C30D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1F49ED: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==14093==    by 0x1F4930: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4548: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F5A68: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A56: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E5E10: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==14093==    by 0x1F13F3: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F0C73: _PyCodec_Lookup (in /usr/bin/python2.7)
==14093==    by 0x1F06A8: ??? (in /usr/bin/python2.7)
==14093==    by 0x1D5E0B: Py_InitializeEx (in /usr/bin/python2.7)
==14093==    by 0x1D4E99: Py_Main (in /usr/bin/python2.7)
==14093==  Block was alloc'd at
==14093==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1F49B8: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==14093==    by 0x1F4930: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4548: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F5A68: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6A56: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E5E10: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==14093==    by 0x1F13F3: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F0C73: _PyCodec_Lookup (in /usr/bin/python2.7)
==14093==    by 0x1F06A8: ??? (in /usr/bin/python2.7)
==14093==    by 0x1D5E0B: Py_InitializeEx (in /usr/bin/python2.7)
==14093==    by 0x1D4E99: Py_Main (in /usr/bin/python2.7)
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x157BFF: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x212203: ??? (in /usr/bin/python2.7)
==14093==    by 0x211E1B: ??? (in /usr/bin/python2.7)
==14093==    by 0x1DCF67: ??? (in /usr/bin/python2.7)
==14093==    by 0x23F860: PyInterpreterState_Clear (in /usr/bin/python2.7)
==14093==    by 0x239934: Py_Finalize (in /usr/bin/python2.7)
==14093==    by 0x1D5073: Py_Main (in /usr/bin/python2.7)
==14093==    by 0x5064B96: (below main) (libc-start.c:310)
==14093==  Address 0x63cd020 is 32 bytes inside a block of size 552 free'd
==14093==    at 0x4C30D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x50C1F41: __fopen_internal (iofopen.c:82)
==14093==    by 0x50C1F41: fopen@@GLIBC_2.2.5 (iofopen.c:89)
==14093==    by 0x1EBD37: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6AE9: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E5E10: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==14093==    by 0x1E79E7: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E777D: PyObject_Call (in /usr/bin/python2.7)
==14093==    by 0x2077FF: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==14093==    by 0x200C09: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x1FB628: PyEval_EvalCode (in /usr/bin/python2.7)
==14093==    by 0x1FB564: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==14093==  Block was alloc'd at
==14093==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x50C1E49: __fopen_internal (iofopen.c:65)
==14093==    by 0x50C1E49: fopen@@GLIBC_2.2.5 (iofopen.c:89)
==14093==    by 0x1EBD37: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E6AE9: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E5E10: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==14093==    by 0x1E79E7: ??? (in /usr/bin/python2.7)
==14093==    by 0x1E777D: PyObject_Call (in /usr/bin/python2.7)
==14093==    by 0x2077FF: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==14093==    by 0x200C09: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x1FB628: PyEval_EvalCode (in /usr/bin/python2.7)
==14093==    by 0x1FB564: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x157BFF: PyObject_Free (in /usr/bin/python2.7)
==14093==    by 0x1EB45A: ??? (in /usr/bin/python2.7)
==14093==    by 0x221D3D: ??? (in /usr/bin/python2.7)
==14093==    by 0x1EB16B: ??? (in /usr/bin/python2.7)
==14093==    by 0x221D27: ??? (in /usr/bin/python2.7)
==14093==    by 0x1EB16B: ??? (in /usr/bin/python2.7)
==14093==    by 0x221D27: ??? (in /usr/bin/python2.7)
==14093==    by 0x1EB16B: ??? (in /usr/bin/python2.7)
==14093==    by 0x237FD3: ??? (in /usr/bin/python2.7)
==14093==    by 0x1EB45A: ??? (in /usr/bin/python2.7)
==14093==    by 0x23F87E: PyInterpreterState_Clear (in /usr/bin/python2.7)
==14093==    by 0x239934: Py_Finalize (in /usr/bin/python2.7)
==14093==  Address 0x63a0020 is 368 bytes inside a block of size 576 free'd
==14093==    at 0x4C31D2F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1D6C71: ??? (in /usr/bin/python2.7)
==14093==    by 0x1D68B4: PyList_Append (in /usr/bin/python2.7)
==14093==    by 0x1F4BAD: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4F61: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EE2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EE2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4A35: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==14093==    by 0x1F49E2: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==14093==    by 0x1F4930: ??? (in /usr/bin/python2.7)
==14093==  Block was alloc'd at
==14093==    at 0x4C31D2F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x1D6C71: ??? (in /usr/bin/python2.7)
==14093==    by 0x1D68B4: PyList_Append (in /usr/bin/python2.7)
==14093==    by 0x1F4BAD: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D18: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EF8: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D18: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EE2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4D7E: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4EE2: ??? (in /usr/bin/python2.7)
==14093==    by 0x1F4A35: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==14093==    by 0x1F49E2: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==14093== 
==14093== Invalid read of size 4
==14093==    at 0x242A17: PyGrammar_RemoveAccelerators (in /usr/bin/python2.7)
==14093==    by 0x2399A0: Py_Finalize (in /usr/bin/python2.7)
==14093==    by 0x1D5073: Py_Main (in /usr/bin/python2.7)
==14093==    by 0x5064B96: (below main) (libc-start.c:310)
==14093==  Address 0x625d020 is 288 bytes inside a block of size 570 free'd
==14093==    at 0x4C30D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x20AC93: PyTokenizer_Free (in /usr/bin/python2.7)
==14093==    by 0x1F9701: ??? (in /usr/bin/python2.7)
==14093==    by 0x2594C9: PyParser_ASTFromString (in /usr/bin/python2.7)
==14093==    by 0x2593B5: PyRun_StringFlags (in /usr/bin/python2.7)
==14093==    by 0x206A94: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x203C37: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x2035FD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x203231: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x203231: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==  Block was alloc'd at
==14093==    at 0x4C31D2F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14093==    by 0x2596DD: PyParser_ParseStringFlagsFilenameEx (in /usr/bin/python2.7)
==14093==    by 0x2594C9: PyParser_ASTFromString (in /usr/bin/python2.7)
==14093==    by 0x2593B5: PyRun_StringFlags (in /usr/bin/python2.7)
==14093==    by 0x206A94: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x203C37: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093==    by 0x2035FD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x203231: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x203231: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==14093==    by 0x1FBD09: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==14093== 
==14093== 
==14093== HEAP SUMMARY:
==14093==     in use at exit: 3,315,980 bytes in 1,854 blocks
==14093==   total heap usage: 19,884 allocs, 18,030 frees, 23,247,903 bytes allocated
==14093== 
==14093== LEAK SUMMARY:
==14093==    definitely lost: 0 bytes in 0 blocks
==14093==    indirectly lost: 0 bytes in 0 blocks
==14093==      possibly lost: 174,047 bytes in 98 blocks
==14093==    still reachable: 3,141,933 bytes in 1,756 blocks
==14093==         suppressed: 0 bytes in 0 blocks
==14093== Rerun with --leak-check=full to see details of leaked memory
==14093== 
==14093== For counts of detected and suppressed errors, rerun with: -v
==14093== Use --track-origins=yes to see where uninitialised values come from
==14093== ERROR SUMMARY: 1884 errors from 95 contexts (suppressed: 0 from 0)
